
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  Cliente: 'Cliente',
  OrdenProduccion: 'OrdenProduccion',
  ProductoOrden: 'ProductoOrden',
  Gasto: 'Gasto',
  ServicioClinica: 'ServicioClinica',
  FotoServicio: 'FotoServicio',
  PedidoConfeccion: 'PedidoConfeccion',
  MedidaSnapshot: 'MedidaSnapshot',
  Medida: 'Medida',
  PlantillaMedida: 'PlantillaMedida',
  Insumo: 'Insumo',
  MovimientoInventario: 'MovimientoInventario'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ClienteScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  nombre: 'nombre',
  documento: 'documento',
  telefono: 'telefono',
  whatsapp: 'whatsapp',
  correo: 'correo',
  direccion: 'direccion',
  contactoNombre: 'contactoNombre',
  contactoTelefono: 'contactoTelefono',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClienteScalarFieldEnum = (typeof ClienteScalarFieldEnum)[keyof typeof ClienteScalarFieldEnum]


export const OrdenProduccionScalarFieldEnum = {
  id: 'id',
  numero: 'numero',
  clienteId: 'clienteId',
  fechaIngreso: 'fechaIngreso',
  fechaEntrega: 'fechaEntrega',
  estado: 'estado',
  notas: 'notas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrdenProduccionScalarFieldEnum = (typeof OrdenProduccionScalarFieldEnum)[keyof typeof OrdenProduccionScalarFieldEnum]


export const ProductoOrdenScalarFieldEnum = {
  id: 'id',
  ordenId: 'ordenId',
  tipoPrenda: 'tipoPrenda',
  cantidad: 'cantidad',
  valorUnitario: 'valorUnitario',
  total: 'total',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductoOrdenScalarFieldEnum = (typeof ProductoOrdenScalarFieldEnum)[keyof typeof ProductoOrdenScalarFieldEnum]


export const GastoScalarFieldEnum = {
  id: 'id',
  concepto: 'concepto',
  categoria: 'categoria',
  tipo: 'tipo',
  monto: 'monto',
  fecha: 'fecha',
  ordenId: 'ordenId',
  servicioClinicaId: 'servicioClinicaId',
  notas: 'notas',
  createdByUserId: 'createdByUserId',
  createdAt: 'createdAt'
} as const

export type GastoScalarFieldEnum = (typeof GastoScalarFieldEnum)[keyof typeof GastoScalarFieldEnum]


export const ServicioClinicaScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  prendaTipo: 'prendaTipo',
  prendaDescripcion: 'prendaDescripcion',
  trabajoSolicitado: 'trabajoSolicitado',
  estado: 'estado',
  fechaRecibido: 'fechaRecibido',
  fechaEntregaEstimada: 'fechaEntregaEstimada',
  valorCotizado: 'valorCotizado',
  anticipo: 'anticipo',
  saldoPendiente: 'saldoPendiente',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServicioClinicaScalarFieldEnum = (typeof ServicioClinicaScalarFieldEnum)[keyof typeof ServicioClinicaScalarFieldEnum]


export const FotoServicioScalarFieldEnum = {
  id: 'id',
  servicioId: 'servicioId',
  tipo: 'tipo',
  url: 'url',
  createdAt: 'createdAt'
} as const

export type FotoServicioScalarFieldEnum = (typeof FotoServicioScalarFieldEnum)[keyof typeof FotoServicioScalarFieldEnum]


export const PedidoConfeccionScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  tipoPrenda: 'tipoPrenda',
  diseño: 'diseño',
  observaciones: 'observaciones',
  fechaEntrega: 'fechaEntrega',
  precio: 'precio',
  estado: 'estado',
  medidaSnapshotId: 'medidaSnapshotId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PedidoConfeccionScalarFieldEnum = (typeof PedidoConfeccionScalarFieldEnum)[keyof typeof PedidoConfeccionScalarFieldEnum]


export const MedidaSnapshotScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  fecha: 'fecha',
  notas: 'notas',
  createdAt: 'createdAt'
} as const

export type MedidaSnapshotScalarFieldEnum = (typeof MedidaSnapshotScalarFieldEnum)[keyof typeof MedidaSnapshotScalarFieldEnum]


export const MedidaScalarFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  nombre: 'nombre',
  valor: 'valor',
  unidad: 'unidad',
  orden: 'orden',
  createdAt: 'createdAt'
} as const

export type MedidaScalarFieldEnum = (typeof MedidaScalarFieldEnum)[keyof typeof MedidaScalarFieldEnum]


export const PlantillaMedidaScalarFieldEnum = {
  id: 'id',
  tipoPrenda: 'tipoPrenda',
  nombre: 'nombre',
  unidadDefault: 'unidadDefault',
  orden: 'orden'
} as const

export type PlantillaMedidaScalarFieldEnum = (typeof PlantillaMedidaScalarFieldEnum)[keyof typeof PlantillaMedidaScalarFieldEnum]


export const InsumoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  unidad: 'unidad',
  costoUnitario: 'costoUnitario',
  stockMinimo: 'stockMinimo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InsumoScalarFieldEnum = (typeof InsumoScalarFieldEnum)[keyof typeof InsumoScalarFieldEnum]


export const MovimientoInventarioScalarFieldEnum = {
  id: 'id',
  insumoId: 'insumoId',
  tipo: 'tipo',
  cantidad: 'cantidad',
  costoUnitario: 'costoUnitario',
  motivo: 'motivo',
  ordenId: 'ordenId',
  createdByUserId: 'createdByUserId',
  createdAt: 'createdAt'
} as const

export type MovimientoInventarioScalarFieldEnum = (typeof MovimientoInventarioScalarFieldEnum)[keyof typeof MovimientoInventarioScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  email: 'email',
  passwordHash: 'passwordHash'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const ClienteOrderByRelevanceFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  documento: 'documento',
  telefono: 'telefono',
  whatsapp: 'whatsapp',
  correo: 'correo',
  direccion: 'direccion',
  contactoNombre: 'contactoNombre',
  contactoTelefono: 'contactoTelefono'
} as const

export type ClienteOrderByRelevanceFieldEnum = (typeof ClienteOrderByRelevanceFieldEnum)[keyof typeof ClienteOrderByRelevanceFieldEnum]


export const OrdenProduccionOrderByRelevanceFieldEnum = {
  id: 'id',
  numero: 'numero',
  clienteId: 'clienteId',
  notas: 'notas'
} as const

export type OrdenProduccionOrderByRelevanceFieldEnum = (typeof OrdenProduccionOrderByRelevanceFieldEnum)[keyof typeof OrdenProduccionOrderByRelevanceFieldEnum]


export const ProductoOrdenOrderByRelevanceFieldEnum = {
  id: 'id',
  ordenId: 'ordenId',
  tipoPrenda: 'tipoPrenda'
} as const

export type ProductoOrdenOrderByRelevanceFieldEnum = (typeof ProductoOrdenOrderByRelevanceFieldEnum)[keyof typeof ProductoOrdenOrderByRelevanceFieldEnum]


export const GastoOrderByRelevanceFieldEnum = {
  id: 'id',
  concepto: 'concepto',
  categoria: 'categoria',
  ordenId: 'ordenId',
  servicioClinicaId: 'servicioClinicaId',
  notas: 'notas',
  createdByUserId: 'createdByUserId'
} as const

export type GastoOrderByRelevanceFieldEnum = (typeof GastoOrderByRelevanceFieldEnum)[keyof typeof GastoOrderByRelevanceFieldEnum]


export const ServicioClinicaOrderByRelevanceFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  prendaTipo: 'prendaTipo',
  prendaDescripcion: 'prendaDescripcion',
  trabajoSolicitado: 'trabajoSolicitado'
} as const

export type ServicioClinicaOrderByRelevanceFieldEnum = (typeof ServicioClinicaOrderByRelevanceFieldEnum)[keyof typeof ServicioClinicaOrderByRelevanceFieldEnum]


export const FotoServicioOrderByRelevanceFieldEnum = {
  id: 'id',
  servicioId: 'servicioId',
  tipo: 'tipo',
  url: 'url'
} as const

export type FotoServicioOrderByRelevanceFieldEnum = (typeof FotoServicioOrderByRelevanceFieldEnum)[keyof typeof FotoServicioOrderByRelevanceFieldEnum]


export const PedidoConfeccionOrderByRelevanceFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  tipoPrenda: 'tipoPrenda',
  diseño: 'diseño',
  observaciones: 'observaciones',
  medidaSnapshotId: 'medidaSnapshotId'
} as const

export type PedidoConfeccionOrderByRelevanceFieldEnum = (typeof PedidoConfeccionOrderByRelevanceFieldEnum)[keyof typeof PedidoConfeccionOrderByRelevanceFieldEnum]


export const MedidaSnapshotOrderByRelevanceFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  notas: 'notas'
} as const

export type MedidaSnapshotOrderByRelevanceFieldEnum = (typeof MedidaSnapshotOrderByRelevanceFieldEnum)[keyof typeof MedidaSnapshotOrderByRelevanceFieldEnum]


export const MedidaOrderByRelevanceFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  nombre: 'nombre',
  valor: 'valor',
  unidad: 'unidad'
} as const

export type MedidaOrderByRelevanceFieldEnum = (typeof MedidaOrderByRelevanceFieldEnum)[keyof typeof MedidaOrderByRelevanceFieldEnum]


export const PlantillaMedidaOrderByRelevanceFieldEnum = {
  id: 'id',
  tipoPrenda: 'tipoPrenda',
  nombre: 'nombre',
  unidadDefault: 'unidadDefault'
} as const

export type PlantillaMedidaOrderByRelevanceFieldEnum = (typeof PlantillaMedidaOrderByRelevanceFieldEnum)[keyof typeof PlantillaMedidaOrderByRelevanceFieldEnum]


export const InsumoOrderByRelevanceFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  unidad: 'unidad'
} as const

export type InsumoOrderByRelevanceFieldEnum = (typeof InsumoOrderByRelevanceFieldEnum)[keyof typeof InsumoOrderByRelevanceFieldEnum]


export const MovimientoInventarioOrderByRelevanceFieldEnum = {
  id: 'id',
  insumoId: 'insumoId',
  tipo: 'tipo',
  motivo: 'motivo',
  ordenId: 'ordenId',
  createdByUserId: 'createdByUserId'
} as const

export type MovimientoInventarioOrderByRelevanceFieldEnum = (typeof MovimientoInventarioOrderByRelevanceFieldEnum)[keyof typeof MovimientoInventarioOrderByRelevanceFieldEnum]

