
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  User: 'User',
  Cliente: 'Cliente',
  OrdenProduccion: 'OrdenProduccion',
  ProductoOrden: 'ProductoOrden',
  Gasto: 'Gasto',
  ServicioClinica: 'ServicioClinica',
  ItemServicioClinica: 'ItemServicioClinica',
  FotoServicio: 'FotoServicio',
  PedidoConfeccion: 'PedidoConfeccion',
  MedidaSnapshot: 'MedidaSnapshot',
  Medida: 'Medida',
  PlantillaMedida: 'PlantillaMedida',
  Insumo: 'Insumo',
  MovimientoInventario: 'MovimientoInventario'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "user" | "cliente" | "ordenProduccion" | "productoOrden" | "gasto" | "servicioClinica" | "itemServicioClinica" | "fotoServicio" | "pedidoConfeccion" | "medidaSnapshot" | "medida" | "plantillaMedida" | "insumo" | "movimientoInventario"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    User: {
      payload: Prisma.$UserPayload<ExtArgs>
      fields: Prisma.UserFieldRefs
      operations: {
        findUnique: {
          args: Prisma.UserFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.UserFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findFirst: {
          args: Prisma.UserFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.UserFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        findMany: {
          args: Prisma.UserFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>[]
        }
        create: {
          args: Prisma.UserCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        createMany: {
          args: Prisma.UserCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.UserDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        update: {
          args: Prisma.UserUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        deleteMany: {
          args: Prisma.UserDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.UserUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.UserUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$UserPayload>
        }
        aggregate: {
          args: Prisma.UserAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateUser>
        }
        groupBy: {
          args: Prisma.UserGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserGroupByOutputType>[]
        }
        count: {
          args: Prisma.UserCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.UserCountAggregateOutputType> | number
        }
      }
    }
    Cliente: {
      payload: Prisma.$ClientePayload<ExtArgs>
      fields: Prisma.ClienteFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ClienteFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ClienteFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>
        }
        findFirst: {
          args: Prisma.ClienteFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ClienteFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>
        }
        findMany: {
          args: Prisma.ClienteFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>[]
        }
        create: {
          args: Prisma.ClienteCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>
        }
        createMany: {
          args: Prisma.ClienteCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ClienteDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>
        }
        update: {
          args: Prisma.ClienteUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>
        }
        deleteMany: {
          args: Prisma.ClienteDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ClienteUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ClienteUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ClientePayload>
        }
        aggregate: {
          args: Prisma.ClienteAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCliente>
        }
        groupBy: {
          args: Prisma.ClienteGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClienteGroupByOutputType>[]
        }
        count: {
          args: Prisma.ClienteCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ClienteCountAggregateOutputType> | number
        }
      }
    }
    OrdenProduccion: {
      payload: Prisma.$OrdenProduccionPayload<ExtArgs>
      fields: Prisma.OrdenProduccionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.OrdenProduccionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.OrdenProduccionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>
        }
        findFirst: {
          args: Prisma.OrdenProduccionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.OrdenProduccionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>
        }
        findMany: {
          args: Prisma.OrdenProduccionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>[]
        }
        create: {
          args: Prisma.OrdenProduccionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>
        }
        createMany: {
          args: Prisma.OrdenProduccionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.OrdenProduccionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>
        }
        update: {
          args: Prisma.OrdenProduccionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>
        }
        deleteMany: {
          args: Prisma.OrdenProduccionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.OrdenProduccionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.OrdenProduccionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrdenProduccionPayload>
        }
        aggregate: {
          args: Prisma.OrdenProduccionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrdenProduccion>
        }
        groupBy: {
          args: Prisma.OrdenProduccionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OrdenProduccionGroupByOutputType>[]
        }
        count: {
          args: Prisma.OrdenProduccionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.OrdenProduccionCountAggregateOutputType> | number
        }
      }
    }
    ProductoOrden: {
      payload: Prisma.$ProductoOrdenPayload<ExtArgs>
      fields: Prisma.ProductoOrdenFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProductoOrdenFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProductoOrdenFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>
        }
        findFirst: {
          args: Prisma.ProductoOrdenFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProductoOrdenFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>
        }
        findMany: {
          args: Prisma.ProductoOrdenFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>[]
        }
        create: {
          args: Prisma.ProductoOrdenCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>
        }
        createMany: {
          args: Prisma.ProductoOrdenCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ProductoOrdenDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>
        }
        update: {
          args: Prisma.ProductoOrdenUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>
        }
        deleteMany: {
          args: Prisma.ProductoOrdenDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProductoOrdenUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ProductoOrdenUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductoOrdenPayload>
        }
        aggregate: {
          args: Prisma.ProductoOrdenAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProductoOrden>
        }
        groupBy: {
          args: Prisma.ProductoOrdenGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductoOrdenGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProductoOrdenCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProductoOrdenCountAggregateOutputType> | number
        }
      }
    }
    Gasto: {
      payload: Prisma.$GastoPayload<ExtArgs>
      fields: Prisma.GastoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.GastoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.GastoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>
        }
        findFirst: {
          args: Prisma.GastoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.GastoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>
        }
        findMany: {
          args: Prisma.GastoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>[]
        }
        create: {
          args: Prisma.GastoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>
        }
        createMany: {
          args: Prisma.GastoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.GastoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>
        }
        update: {
          args: Prisma.GastoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>
        }
        deleteMany: {
          args: Prisma.GastoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.GastoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.GastoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$GastoPayload>
        }
        aggregate: {
          args: Prisma.GastoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateGasto>
        }
        groupBy: {
          args: Prisma.GastoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GastoGroupByOutputType>[]
        }
        count: {
          args: Prisma.GastoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.GastoCountAggregateOutputType> | number
        }
      }
    }
    ServicioClinica: {
      payload: Prisma.$ServicioClinicaPayload<ExtArgs>
      fields: Prisma.ServicioClinicaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ServicioClinicaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ServicioClinicaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>
        }
        findFirst: {
          args: Prisma.ServicioClinicaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ServicioClinicaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>
        }
        findMany: {
          args: Prisma.ServicioClinicaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>[]
        }
        create: {
          args: Prisma.ServicioClinicaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>
        }
        createMany: {
          args: Prisma.ServicioClinicaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ServicioClinicaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>
        }
        update: {
          args: Prisma.ServicioClinicaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>
        }
        deleteMany: {
          args: Prisma.ServicioClinicaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ServicioClinicaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ServicioClinicaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ServicioClinicaPayload>
        }
        aggregate: {
          args: Prisma.ServicioClinicaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateServicioClinica>
        }
        groupBy: {
          args: Prisma.ServicioClinicaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServicioClinicaGroupByOutputType>[]
        }
        count: {
          args: Prisma.ServicioClinicaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ServicioClinicaCountAggregateOutputType> | number
        }
      }
    }
    ItemServicioClinica: {
      payload: Prisma.$ItemServicioClinicaPayload<ExtArgs>
      fields: Prisma.ItemServicioClinicaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ItemServicioClinicaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ItemServicioClinicaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>
        }
        findFirst: {
          args: Prisma.ItemServicioClinicaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ItemServicioClinicaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>
        }
        findMany: {
          args: Prisma.ItemServicioClinicaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>[]
        }
        create: {
          args: Prisma.ItemServicioClinicaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>
        }
        createMany: {
          args: Prisma.ItemServicioClinicaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.ItemServicioClinicaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>
        }
        update: {
          args: Prisma.ItemServicioClinicaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>
        }
        deleteMany: {
          args: Prisma.ItemServicioClinicaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ItemServicioClinicaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.ItemServicioClinicaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ItemServicioClinicaPayload>
        }
        aggregate: {
          args: Prisma.ItemServicioClinicaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateItemServicioClinica>
        }
        groupBy: {
          args: Prisma.ItemServicioClinicaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ItemServicioClinicaGroupByOutputType>[]
        }
        count: {
          args: Prisma.ItemServicioClinicaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ItemServicioClinicaCountAggregateOutputType> | number
        }
      }
    }
    FotoServicio: {
      payload: Prisma.$FotoServicioPayload<ExtArgs>
      fields: Prisma.FotoServicioFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FotoServicioFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FotoServicioFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>
        }
        findFirst: {
          args: Prisma.FotoServicioFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FotoServicioFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>
        }
        findMany: {
          args: Prisma.FotoServicioFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>[]
        }
        create: {
          args: Prisma.FotoServicioCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>
        }
        createMany: {
          args: Prisma.FotoServicioCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.FotoServicioDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>
        }
        update: {
          args: Prisma.FotoServicioUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>
        }
        deleteMany: {
          args: Prisma.FotoServicioDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FotoServicioUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.FotoServicioUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FotoServicioPayload>
        }
        aggregate: {
          args: Prisma.FotoServicioAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFotoServicio>
        }
        groupBy: {
          args: Prisma.FotoServicioGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FotoServicioGroupByOutputType>[]
        }
        count: {
          args: Prisma.FotoServicioCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FotoServicioCountAggregateOutputType> | number
        }
      }
    }
    PedidoConfeccion: {
      payload: Prisma.$PedidoConfeccionPayload<ExtArgs>
      fields: Prisma.PedidoConfeccionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PedidoConfeccionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PedidoConfeccionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>
        }
        findFirst: {
          args: Prisma.PedidoConfeccionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PedidoConfeccionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>
        }
        findMany: {
          args: Prisma.PedidoConfeccionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>[]
        }
        create: {
          args: Prisma.PedidoConfeccionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>
        }
        createMany: {
          args: Prisma.PedidoConfeccionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.PedidoConfeccionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>
        }
        update: {
          args: Prisma.PedidoConfeccionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>
        }
        deleteMany: {
          args: Prisma.PedidoConfeccionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PedidoConfeccionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.PedidoConfeccionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PedidoConfeccionPayload>
        }
        aggregate: {
          args: Prisma.PedidoConfeccionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePedidoConfeccion>
        }
        groupBy: {
          args: Prisma.PedidoConfeccionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PedidoConfeccionGroupByOutputType>[]
        }
        count: {
          args: Prisma.PedidoConfeccionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PedidoConfeccionCountAggregateOutputType> | number
        }
      }
    }
    MedidaSnapshot: {
      payload: Prisma.$MedidaSnapshotPayload<ExtArgs>
      fields: Prisma.MedidaSnapshotFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MedidaSnapshotFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MedidaSnapshotFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>
        }
        findFirst: {
          args: Prisma.MedidaSnapshotFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MedidaSnapshotFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>
        }
        findMany: {
          args: Prisma.MedidaSnapshotFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>[]
        }
        create: {
          args: Prisma.MedidaSnapshotCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>
        }
        createMany: {
          args: Prisma.MedidaSnapshotCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.MedidaSnapshotDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>
        }
        update: {
          args: Prisma.MedidaSnapshotUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>
        }
        deleteMany: {
          args: Prisma.MedidaSnapshotDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MedidaSnapshotUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.MedidaSnapshotUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaSnapshotPayload>
        }
        aggregate: {
          args: Prisma.MedidaSnapshotAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMedidaSnapshot>
        }
        groupBy: {
          args: Prisma.MedidaSnapshotGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MedidaSnapshotGroupByOutputType>[]
        }
        count: {
          args: Prisma.MedidaSnapshotCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MedidaSnapshotCountAggregateOutputType> | number
        }
      }
    }
    Medida: {
      payload: Prisma.$MedidaPayload<ExtArgs>
      fields: Prisma.MedidaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MedidaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MedidaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>
        }
        findFirst: {
          args: Prisma.MedidaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MedidaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>
        }
        findMany: {
          args: Prisma.MedidaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>[]
        }
        create: {
          args: Prisma.MedidaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>
        }
        createMany: {
          args: Prisma.MedidaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.MedidaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>
        }
        update: {
          args: Prisma.MedidaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>
        }
        deleteMany: {
          args: Prisma.MedidaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MedidaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.MedidaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MedidaPayload>
        }
        aggregate: {
          args: Prisma.MedidaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMedida>
        }
        groupBy: {
          args: Prisma.MedidaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MedidaGroupByOutputType>[]
        }
        count: {
          args: Prisma.MedidaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MedidaCountAggregateOutputType> | number
        }
      }
    }
    PlantillaMedida: {
      payload: Prisma.$PlantillaMedidaPayload<ExtArgs>
      fields: Prisma.PlantillaMedidaFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PlantillaMedidaFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PlantillaMedidaFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>
        }
        findFirst: {
          args: Prisma.PlantillaMedidaFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PlantillaMedidaFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>
        }
        findMany: {
          args: Prisma.PlantillaMedidaFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>[]
        }
        create: {
          args: Prisma.PlantillaMedidaCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>
        }
        createMany: {
          args: Prisma.PlantillaMedidaCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.PlantillaMedidaDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>
        }
        update: {
          args: Prisma.PlantillaMedidaUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>
        }
        deleteMany: {
          args: Prisma.PlantillaMedidaDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PlantillaMedidaUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.PlantillaMedidaUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PlantillaMedidaPayload>
        }
        aggregate: {
          args: Prisma.PlantillaMedidaAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePlantillaMedida>
        }
        groupBy: {
          args: Prisma.PlantillaMedidaGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PlantillaMedidaGroupByOutputType>[]
        }
        count: {
          args: Prisma.PlantillaMedidaCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PlantillaMedidaCountAggregateOutputType> | number
        }
      }
    }
    Insumo: {
      payload: Prisma.$InsumoPayload<ExtArgs>
      fields: Prisma.InsumoFieldRefs
      operations: {
        findUnique: {
          args: Prisma.InsumoFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.InsumoFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>
        }
        findFirst: {
          args: Prisma.InsumoFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.InsumoFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>
        }
        findMany: {
          args: Prisma.InsumoFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>[]
        }
        create: {
          args: Prisma.InsumoCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>
        }
        createMany: {
          args: Prisma.InsumoCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.InsumoDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>
        }
        update: {
          args: Prisma.InsumoUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>
        }
        deleteMany: {
          args: Prisma.InsumoDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.InsumoUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.InsumoUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$InsumoPayload>
        }
        aggregate: {
          args: Prisma.InsumoAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateInsumo>
        }
        groupBy: {
          args: Prisma.InsumoGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InsumoGroupByOutputType>[]
        }
        count: {
          args: Prisma.InsumoCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.InsumoCountAggregateOutputType> | number
        }
      }
    }
    MovimientoInventario: {
      payload: Prisma.$MovimientoInventarioPayload<ExtArgs>
      fields: Prisma.MovimientoInventarioFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MovimientoInventarioFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MovimientoInventarioFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>
        }
        findFirst: {
          args: Prisma.MovimientoInventarioFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MovimientoInventarioFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>
        }
        findMany: {
          args: Prisma.MovimientoInventarioFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>[]
        }
        create: {
          args: Prisma.MovimientoInventarioCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>
        }
        createMany: {
          args: Prisma.MovimientoInventarioCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.MovimientoInventarioDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>
        }
        update: {
          args: Prisma.MovimientoInventarioUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>
        }
        deleteMany: {
          args: Prisma.MovimientoInventarioDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MovimientoInventarioUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.MovimientoInventarioUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MovimientoInventarioPayload>
        }
        aggregate: {
          args: Prisma.MovimientoInventarioAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMovimientoInventario>
        }
        groupBy: {
          args: Prisma.MovimientoInventarioGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MovimientoInventarioGroupByOutputType>[]
        }
        count: {
          args: Prisma.MovimientoInventarioCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MovimientoInventarioCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  email: 'email',
  passwordHash: 'passwordHash',
  role: 'role',
  activo: 'activo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const ClienteScalarFieldEnum = {
  id: 'id',
  tipo: 'tipo',
  nombre: 'nombre',
  documento: 'documento',
  telefono: 'telefono',
  whatsapp: 'whatsapp',
  correo: 'correo',
  direccion: 'direccion',
  contactoNombre: 'contactoNombre',
  contactoTelefono: 'contactoTelefono',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClienteScalarFieldEnum = (typeof ClienteScalarFieldEnum)[keyof typeof ClienteScalarFieldEnum]


export const OrdenProduccionScalarFieldEnum = {
  id: 'id',
  numero: 'numero',
  clienteId: 'clienteId',
  fechaIngreso: 'fechaIngreso',
  fechaEntrega: 'fechaEntrega',
  estado: 'estado',
  notas: 'notas',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrdenProduccionScalarFieldEnum = (typeof OrdenProduccionScalarFieldEnum)[keyof typeof OrdenProduccionScalarFieldEnum]


export const ProductoOrdenScalarFieldEnum = {
  id: 'id',
  ordenId: 'ordenId',
  tipoPrenda: 'tipoPrenda',
  cantidad: 'cantidad',
  valorUnitario: 'valorUnitario',
  total: 'total',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProductoOrdenScalarFieldEnum = (typeof ProductoOrdenScalarFieldEnum)[keyof typeof ProductoOrdenScalarFieldEnum]


export const GastoScalarFieldEnum = {
  id: 'id',
  concepto: 'concepto',
  categoria: 'categoria',
  tipo: 'tipo',
  monto: 'monto',
  fecha: 'fecha',
  ordenId: 'ordenId',
  servicioClinicaId: 'servicioClinicaId',
  notas: 'notas',
  createdByUserId: 'createdByUserId',
  createdAt: 'createdAt'
} as const

export type GastoScalarFieldEnum = (typeof GastoScalarFieldEnum)[keyof typeof GastoScalarFieldEnum]


export const ServicioClinicaScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  prendaTipo: 'prendaTipo',
  prendaDescripcion: 'prendaDescripcion',
  trabajoSolicitado: 'trabajoSolicitado',
  estado: 'estado',
  fechaRecibido: 'fechaRecibido',
  fechaEntregaEstimada: 'fechaEntregaEstimada',
  valorCotizado: 'valorCotizado',
  anticipo: 'anticipo',
  saldoPendiente: 'saldoPendiente',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ServicioClinicaScalarFieldEnum = (typeof ServicioClinicaScalarFieldEnum)[keyof typeof ServicioClinicaScalarFieldEnum]


export const ItemServicioClinicaScalarFieldEnum = {
  id: 'id',
  servicioId: 'servicioId',
  prendaTipo: 'prendaTipo',
  prendaDescripcion: 'prendaDescripcion',
  trabajoSolicitado: 'trabajoSolicitado',
  valorCotizado: 'valorCotizado',
  anticipo: 'anticipo',
  saldoPendiente: 'saldoPendiente',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ItemServicioClinicaScalarFieldEnum = (typeof ItemServicioClinicaScalarFieldEnum)[keyof typeof ItemServicioClinicaScalarFieldEnum]


export const FotoServicioScalarFieldEnum = {
  id: 'id',
  servicioId: 'servicioId',
  tipo: 'tipo',
  url: 'url',
  createdAt: 'createdAt'
} as const

export type FotoServicioScalarFieldEnum = (typeof FotoServicioScalarFieldEnum)[keyof typeof FotoServicioScalarFieldEnum]


export const PedidoConfeccionScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  tipoPrenda: 'tipoPrenda',
  diseño: 'diseño',
  observaciones: 'observaciones',
  fechaEntrega: 'fechaEntrega',
  precio: 'precio',
  estado: 'estado',
  medidaSnapshotId: 'medidaSnapshotId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PedidoConfeccionScalarFieldEnum = (typeof PedidoConfeccionScalarFieldEnum)[keyof typeof PedidoConfeccionScalarFieldEnum]


export const MedidaSnapshotScalarFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  fecha: 'fecha',
  notas: 'notas',
  createdAt: 'createdAt'
} as const

export type MedidaSnapshotScalarFieldEnum = (typeof MedidaSnapshotScalarFieldEnum)[keyof typeof MedidaSnapshotScalarFieldEnum]


export const MedidaScalarFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  nombre: 'nombre',
  valor: 'valor',
  unidad: 'unidad',
  orden: 'orden',
  createdAt: 'createdAt'
} as const

export type MedidaScalarFieldEnum = (typeof MedidaScalarFieldEnum)[keyof typeof MedidaScalarFieldEnum]


export const PlantillaMedidaScalarFieldEnum = {
  id: 'id',
  tipoPrenda: 'tipoPrenda',
  nombre: 'nombre',
  unidadDefault: 'unidadDefault',
  orden: 'orden'
} as const

export type PlantillaMedidaScalarFieldEnum = (typeof PlantillaMedidaScalarFieldEnum)[keyof typeof PlantillaMedidaScalarFieldEnum]


export const InsumoScalarFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  unidad: 'unidad',
  costoUnitario: 'costoUnitario',
  stockMinimo: 'stockMinimo',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type InsumoScalarFieldEnum = (typeof InsumoScalarFieldEnum)[keyof typeof InsumoScalarFieldEnum]


export const MovimientoInventarioScalarFieldEnum = {
  id: 'id',
  insumoId: 'insumoId',
  tipo: 'tipo',
  cantidad: 'cantidad',
  costoUnitario: 'costoUnitario',
  motivo: 'motivo',
  ordenId: 'ordenId',
  createdByUserId: 'createdByUserId',
  createdAt: 'createdAt'
} as const

export type MovimientoInventarioScalarFieldEnum = (typeof MovimientoInventarioScalarFieldEnum)[keyof typeof MovimientoInventarioScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const UserOrderByRelevanceFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  email: 'email',
  passwordHash: 'passwordHash'
} as const

export type UserOrderByRelevanceFieldEnum = (typeof UserOrderByRelevanceFieldEnum)[keyof typeof UserOrderByRelevanceFieldEnum]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const ClienteOrderByRelevanceFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  documento: 'documento',
  telefono: 'telefono',
  whatsapp: 'whatsapp',
  correo: 'correo',
  direccion: 'direccion',
  contactoNombre: 'contactoNombre',
  contactoTelefono: 'contactoTelefono'
} as const

export type ClienteOrderByRelevanceFieldEnum = (typeof ClienteOrderByRelevanceFieldEnum)[keyof typeof ClienteOrderByRelevanceFieldEnum]


export const OrdenProduccionOrderByRelevanceFieldEnum = {
  id: 'id',
  numero: 'numero',
  clienteId: 'clienteId',
  notas: 'notas'
} as const

export type OrdenProduccionOrderByRelevanceFieldEnum = (typeof OrdenProduccionOrderByRelevanceFieldEnum)[keyof typeof OrdenProduccionOrderByRelevanceFieldEnum]


export const ProductoOrdenOrderByRelevanceFieldEnum = {
  id: 'id',
  ordenId: 'ordenId',
  tipoPrenda: 'tipoPrenda'
} as const

export type ProductoOrdenOrderByRelevanceFieldEnum = (typeof ProductoOrdenOrderByRelevanceFieldEnum)[keyof typeof ProductoOrdenOrderByRelevanceFieldEnum]


export const GastoOrderByRelevanceFieldEnum = {
  id: 'id',
  concepto: 'concepto',
  categoria: 'categoria',
  ordenId: 'ordenId',
  servicioClinicaId: 'servicioClinicaId',
  notas: 'notas',
  createdByUserId: 'createdByUserId'
} as const

export type GastoOrderByRelevanceFieldEnum = (typeof GastoOrderByRelevanceFieldEnum)[keyof typeof GastoOrderByRelevanceFieldEnum]


export const ServicioClinicaOrderByRelevanceFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  prendaTipo: 'prendaTipo',
  prendaDescripcion: 'prendaDescripcion',
  trabajoSolicitado: 'trabajoSolicitado'
} as const

export type ServicioClinicaOrderByRelevanceFieldEnum = (typeof ServicioClinicaOrderByRelevanceFieldEnum)[keyof typeof ServicioClinicaOrderByRelevanceFieldEnum]


export const ItemServicioClinicaOrderByRelevanceFieldEnum = {
  id: 'id',
  servicioId: 'servicioId',
  prendaTipo: 'prendaTipo',
  prendaDescripcion: 'prendaDescripcion',
  trabajoSolicitado: 'trabajoSolicitado'
} as const

export type ItemServicioClinicaOrderByRelevanceFieldEnum = (typeof ItemServicioClinicaOrderByRelevanceFieldEnum)[keyof typeof ItemServicioClinicaOrderByRelevanceFieldEnum]


export const FotoServicioOrderByRelevanceFieldEnum = {
  id: 'id',
  servicioId: 'servicioId',
  tipo: 'tipo',
  url: 'url'
} as const

export type FotoServicioOrderByRelevanceFieldEnum = (typeof FotoServicioOrderByRelevanceFieldEnum)[keyof typeof FotoServicioOrderByRelevanceFieldEnum]


export const PedidoConfeccionOrderByRelevanceFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  tipoPrenda: 'tipoPrenda',
  diseño: 'diseño',
  observaciones: 'observaciones',
  medidaSnapshotId: 'medidaSnapshotId'
} as const

export type PedidoConfeccionOrderByRelevanceFieldEnum = (typeof PedidoConfeccionOrderByRelevanceFieldEnum)[keyof typeof PedidoConfeccionOrderByRelevanceFieldEnum]


export const MedidaSnapshotOrderByRelevanceFieldEnum = {
  id: 'id',
  clienteId: 'clienteId',
  notas: 'notas'
} as const

export type MedidaSnapshotOrderByRelevanceFieldEnum = (typeof MedidaSnapshotOrderByRelevanceFieldEnum)[keyof typeof MedidaSnapshotOrderByRelevanceFieldEnum]


export const MedidaOrderByRelevanceFieldEnum = {
  id: 'id',
  snapshotId: 'snapshotId',
  nombre: 'nombre',
  valor: 'valor',
  unidad: 'unidad'
} as const

export type MedidaOrderByRelevanceFieldEnum = (typeof MedidaOrderByRelevanceFieldEnum)[keyof typeof MedidaOrderByRelevanceFieldEnum]


export const PlantillaMedidaOrderByRelevanceFieldEnum = {
  id: 'id',
  tipoPrenda: 'tipoPrenda',
  nombre: 'nombre',
  unidadDefault: 'unidadDefault'
} as const

export type PlantillaMedidaOrderByRelevanceFieldEnum = (typeof PlantillaMedidaOrderByRelevanceFieldEnum)[keyof typeof PlantillaMedidaOrderByRelevanceFieldEnum]


export const InsumoOrderByRelevanceFieldEnum = {
  id: 'id',
  nombre: 'nombre',
  unidad: 'unidad'
} as const

export type InsumoOrderByRelevanceFieldEnum = (typeof InsumoOrderByRelevanceFieldEnum)[keyof typeof InsumoOrderByRelevanceFieldEnum]


export const MovimientoInventarioOrderByRelevanceFieldEnum = {
  id: 'id',
  insumoId: 'insumoId',
  tipo: 'tipo',
  motivo: 'motivo',
  ordenId: 'ordenId',
  createdByUserId: 'createdByUserId'
} as const

export type MovimientoInventarioOrderByRelevanceFieldEnum = (typeof MovimientoInventarioOrderByRelevanceFieldEnum)[keyof typeof MovimientoInventarioOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'Role'
 */
export type EnumRoleFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Role'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'TipoCliente'
 */
export type EnumTipoClienteFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TipoCliente'>
    


/**
 * Reference to a field of type 'EstadoOrden'
 */
export type EnumEstadoOrdenFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'EstadoOrden'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Decimal'
 */
export type DecimalFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Decimal'>
    


/**
 * Reference to a field of type 'TipoGasto'
 */
export type EnumTipoGastoFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'TipoGasto'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  user?: Prisma.UserOmit
  cliente?: Prisma.ClienteOmit
  ordenProduccion?: Prisma.OrdenProduccionOmit
  productoOrden?: Prisma.ProductoOrdenOmit
  gasto?: Prisma.GastoOmit
  servicioClinica?: Prisma.ServicioClinicaOmit
  itemServicioClinica?: Prisma.ItemServicioClinicaOmit
  fotoServicio?: Prisma.FotoServicioOmit
  pedidoConfeccion?: Prisma.PedidoConfeccionOmit
  medidaSnapshot?: Prisma.MedidaSnapshotOmit
  medida?: Prisma.MedidaOmit
  plantillaMedida?: Prisma.PlantillaMedidaOmit
  insumo?: Prisma.InsumoOmit
  movimientoInventario?: Prisma.MovimientoInventarioOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

