
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ItemServicioClinica` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ItemServicioClinica
 * 
 */
export type ItemServicioClinicaModel = runtime.Types.Result.DefaultSelection<Prisma.$ItemServicioClinicaPayload>

export type AggregateItemServicioClinica = {
  _count: ItemServicioClinicaCountAggregateOutputType | null
  _avg: ItemServicioClinicaAvgAggregateOutputType | null
  _sum: ItemServicioClinicaSumAggregateOutputType | null
  _min: ItemServicioClinicaMinAggregateOutputType | null
  _max: ItemServicioClinicaMaxAggregateOutputType | null
}

export type ItemServicioClinicaAvgAggregateOutputType = {
  valorCotizado: runtime.Decimal | null
  anticipo: runtime.Decimal | null
  saldoPendiente: runtime.Decimal | null
}

export type ItemServicioClinicaSumAggregateOutputType = {
  valorCotizado: runtime.Decimal | null
  anticipo: runtime.Decimal | null
  saldoPendiente: runtime.Decimal | null
}

export type ItemServicioClinicaMinAggregateOutputType = {
  id: string | null
  servicioId: string | null
  prendaTipo: string | null
  prendaDescripcion: string | null
  trabajoSolicitado: string | null
  valorCotizado: runtime.Decimal | null
  anticipo: runtime.Decimal | null
  saldoPendiente: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ItemServicioClinicaMaxAggregateOutputType = {
  id: string | null
  servicioId: string | null
  prendaTipo: string | null
  prendaDescripcion: string | null
  trabajoSolicitado: string | null
  valorCotizado: runtime.Decimal | null
  anticipo: runtime.Decimal | null
  saldoPendiente: runtime.Decimal | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ItemServicioClinicaCountAggregateOutputType = {
  id: number
  servicioId: number
  prendaTipo: number
  prendaDescripcion: number
  trabajoSolicitado: number
  valorCotizado: number
  anticipo: number
  saldoPendiente: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ItemServicioClinicaAvgAggregateInputType = {
  valorCotizado?: true
  anticipo?: true
  saldoPendiente?: true
}

export type ItemServicioClinicaSumAggregateInputType = {
  valorCotizado?: true
  anticipo?: true
  saldoPendiente?: true
}

export type ItemServicioClinicaMinAggregateInputType = {
  id?: true
  servicioId?: true
  prendaTipo?: true
  prendaDescripcion?: true
  trabajoSolicitado?: true
  valorCotizado?: true
  anticipo?: true
  saldoPendiente?: true
  createdAt?: true
  updatedAt?: true
}

export type ItemServicioClinicaMaxAggregateInputType = {
  id?: true
  servicioId?: true
  prendaTipo?: true
  prendaDescripcion?: true
  trabajoSolicitado?: true
  valorCotizado?: true
  anticipo?: true
  saldoPendiente?: true
  createdAt?: true
  updatedAt?: true
}

export type ItemServicioClinicaCountAggregateInputType = {
  id?: true
  servicioId?: true
  prendaTipo?: true
  prendaDescripcion?: true
  trabajoSolicitado?: true
  valorCotizado?: true
  anticipo?: true
  saldoPendiente?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ItemServicioClinicaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemServicioClinica to aggregate.
   */
  where?: Prisma.ItemServicioClinicaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemServicioClinicas to fetch.
   */
  orderBy?: Prisma.ItemServicioClinicaOrderByWithRelationInput | Prisma.ItemServicioClinicaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ItemServicioClinicaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemServicioClinicas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemServicioClinicas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ItemServicioClinicas
  **/
  _count?: true | ItemServicioClinicaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ItemServicioClinicaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ItemServicioClinicaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ItemServicioClinicaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ItemServicioClinicaMaxAggregateInputType
}

export type GetItemServicioClinicaAggregateType<T extends ItemServicioClinicaAggregateArgs> = {
      [P in keyof T & keyof AggregateItemServicioClinica]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateItemServicioClinica[P]>
    : Prisma.GetScalarType<T[P], AggregateItemServicioClinica[P]>
}




export type ItemServicioClinicaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ItemServicioClinicaWhereInput
  orderBy?: Prisma.ItemServicioClinicaOrderByWithAggregationInput | Prisma.ItemServicioClinicaOrderByWithAggregationInput[]
  by: Prisma.ItemServicioClinicaScalarFieldEnum[] | Prisma.ItemServicioClinicaScalarFieldEnum
  having?: Prisma.ItemServicioClinicaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ItemServicioClinicaCountAggregateInputType | true
  _avg?: ItemServicioClinicaAvgAggregateInputType
  _sum?: ItemServicioClinicaSumAggregateInputType
  _min?: ItemServicioClinicaMinAggregateInputType
  _max?: ItemServicioClinicaMaxAggregateInputType
}

export type ItemServicioClinicaGroupByOutputType = {
  id: string
  servicioId: string
  prendaTipo: string
  prendaDescripcion: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal
  anticipo: runtime.Decimal
  saldoPendiente: runtime.Decimal
  createdAt: Date
  updatedAt: Date
  _count: ItemServicioClinicaCountAggregateOutputType | null
  _avg: ItemServicioClinicaAvgAggregateOutputType | null
  _sum: ItemServicioClinicaSumAggregateOutputType | null
  _min: ItemServicioClinicaMinAggregateOutputType | null
  _max: ItemServicioClinicaMaxAggregateOutputType | null
}

export type GetItemServicioClinicaGroupByPayload<T extends ItemServicioClinicaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ItemServicioClinicaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ItemServicioClinicaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ItemServicioClinicaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ItemServicioClinicaGroupByOutputType[P]>
      }
    >
  >



export type ItemServicioClinicaWhereInput = {
  AND?: Prisma.ItemServicioClinicaWhereInput | Prisma.ItemServicioClinicaWhereInput[]
  OR?: Prisma.ItemServicioClinicaWhereInput[]
  NOT?: Prisma.ItemServicioClinicaWhereInput | Prisma.ItemServicioClinicaWhereInput[]
  id?: Prisma.StringFilter<"ItemServicioClinica"> | string
  servicioId?: Prisma.StringFilter<"ItemServicioClinica"> | string
  prendaTipo?: Prisma.StringFilter<"ItemServicioClinica"> | string
  prendaDescripcion?: Prisma.StringNullableFilter<"ItemServicioClinica"> | string | null
  trabajoSolicitado?: Prisma.StringFilter<"ItemServicioClinica"> | string
  valorCotizado?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"ItemServicioClinica"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ItemServicioClinica"> | Date | string
  servicio?: Prisma.XOR<Prisma.ServicioClinicaScalarRelationFilter, Prisma.ServicioClinicaWhereInput>
}

export type ItemServicioClinicaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  servicioId?: Prisma.SortOrder
  prendaTipo?: Prisma.SortOrder
  prendaDescripcion?: Prisma.SortOrderInput | Prisma.SortOrder
  trabajoSolicitado?: Prisma.SortOrder
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  servicio?: Prisma.ServicioClinicaOrderByWithRelationInput
  _relevance?: Prisma.ItemServicioClinicaOrderByRelevanceInput
}

export type ItemServicioClinicaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ItemServicioClinicaWhereInput | Prisma.ItemServicioClinicaWhereInput[]
  OR?: Prisma.ItemServicioClinicaWhereInput[]
  NOT?: Prisma.ItemServicioClinicaWhereInput | Prisma.ItemServicioClinicaWhereInput[]
  servicioId?: Prisma.StringFilter<"ItemServicioClinica"> | string
  prendaTipo?: Prisma.StringFilter<"ItemServicioClinica"> | string
  prendaDescripcion?: Prisma.StringNullableFilter<"ItemServicioClinica"> | string | null
  trabajoSolicitado?: Prisma.StringFilter<"ItemServicioClinica"> | string
  valorCotizado?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"ItemServicioClinica"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ItemServicioClinica"> | Date | string
  servicio?: Prisma.XOR<Prisma.ServicioClinicaScalarRelationFilter, Prisma.ServicioClinicaWhereInput>
}, "id">

export type ItemServicioClinicaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  servicioId?: Prisma.SortOrder
  prendaTipo?: Prisma.SortOrder
  prendaDescripcion?: Prisma.SortOrderInput | Prisma.SortOrder
  trabajoSolicitado?: Prisma.SortOrder
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ItemServicioClinicaCountOrderByAggregateInput
  _avg?: Prisma.ItemServicioClinicaAvgOrderByAggregateInput
  _max?: Prisma.ItemServicioClinicaMaxOrderByAggregateInput
  _min?: Prisma.ItemServicioClinicaMinOrderByAggregateInput
  _sum?: Prisma.ItemServicioClinicaSumOrderByAggregateInput
}

export type ItemServicioClinicaScalarWhereWithAggregatesInput = {
  AND?: Prisma.ItemServicioClinicaScalarWhereWithAggregatesInput | Prisma.ItemServicioClinicaScalarWhereWithAggregatesInput[]
  OR?: Prisma.ItemServicioClinicaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ItemServicioClinicaScalarWhereWithAggregatesInput | Prisma.ItemServicioClinicaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ItemServicioClinica"> | string
  servicioId?: Prisma.StringWithAggregatesFilter<"ItemServicioClinica"> | string
  prendaTipo?: Prisma.StringWithAggregatesFilter<"ItemServicioClinica"> | string
  prendaDescripcion?: Prisma.StringNullableWithAggregatesFilter<"ItemServicioClinica"> | string | null
  trabajoSolicitado?: Prisma.StringWithAggregatesFilter<"ItemServicioClinica"> | string
  valorCotizado?: Prisma.DecimalWithAggregatesFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalWithAggregatesFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalWithAggregatesFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ItemServicioClinica"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ItemServicioClinica"> | Date | string
}

export type ItemServicioClinicaCreateInput = {
  id?: string
  prendaTipo: string
  prendaDescripcion?: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
  servicio: Prisma.ServicioClinicaCreateNestedOneWithoutItemsInput
}

export type ItemServicioClinicaUncheckedCreateInput = {
  id?: string
  servicioId: string
  prendaTipo: string
  prendaDescripcion?: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemServicioClinicaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  servicio?: Prisma.ServicioClinicaUpdateOneRequiredWithoutItemsNestedInput
}

export type ItemServicioClinicaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  servicioId?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemServicioClinicaCreateManyInput = {
  id?: string
  servicioId: string
  prendaTipo: string
  prendaDescripcion?: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemServicioClinicaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemServicioClinicaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  servicioId?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemServicioClinicaListRelationFilter = {
  every?: Prisma.ItemServicioClinicaWhereInput
  some?: Prisma.ItemServicioClinicaWhereInput
  none?: Prisma.ItemServicioClinicaWhereInput
}

export type ItemServicioClinicaOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItemServicioClinicaOrderByRelevanceInput = {
  fields: Prisma.ItemServicioClinicaOrderByRelevanceFieldEnum | Prisma.ItemServicioClinicaOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ItemServicioClinicaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  servicioId?: Prisma.SortOrder
  prendaTipo?: Prisma.SortOrder
  prendaDescripcion?: Prisma.SortOrder
  trabajoSolicitado?: Prisma.SortOrder
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ItemServicioClinicaAvgOrderByAggregateInput = {
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
}

export type ItemServicioClinicaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  servicioId?: Prisma.SortOrder
  prendaTipo?: Prisma.SortOrder
  prendaDescripcion?: Prisma.SortOrder
  trabajoSolicitado?: Prisma.SortOrder
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ItemServicioClinicaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  servicioId?: Prisma.SortOrder
  prendaTipo?: Prisma.SortOrder
  prendaDescripcion?: Prisma.SortOrder
  trabajoSolicitado?: Prisma.SortOrder
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ItemServicioClinicaSumOrderByAggregateInput = {
  valorCotizado?: Prisma.SortOrder
  anticipo?: Prisma.SortOrder
  saldoPendiente?: Prisma.SortOrder
}

export type ItemServicioClinicaCreateNestedManyWithoutServicioInput = {
  create?: Prisma.XOR<Prisma.ItemServicioClinicaCreateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput> | Prisma.ItemServicioClinicaCreateWithoutServicioInput[] | Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput[]
  connectOrCreate?: Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput | Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput[]
  createMany?: Prisma.ItemServicioClinicaCreateManyServicioInputEnvelope
  connect?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
}

export type ItemServicioClinicaUncheckedCreateNestedManyWithoutServicioInput = {
  create?: Prisma.XOR<Prisma.ItemServicioClinicaCreateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput> | Prisma.ItemServicioClinicaCreateWithoutServicioInput[] | Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput[]
  connectOrCreate?: Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput | Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput[]
  createMany?: Prisma.ItemServicioClinicaCreateManyServicioInputEnvelope
  connect?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
}

export type ItemServicioClinicaUpdateManyWithoutServicioNestedInput = {
  create?: Prisma.XOR<Prisma.ItemServicioClinicaCreateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput> | Prisma.ItemServicioClinicaCreateWithoutServicioInput[] | Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput[]
  connectOrCreate?: Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput | Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput[]
  upsert?: Prisma.ItemServicioClinicaUpsertWithWhereUniqueWithoutServicioInput | Prisma.ItemServicioClinicaUpsertWithWhereUniqueWithoutServicioInput[]
  createMany?: Prisma.ItemServicioClinicaCreateManyServicioInputEnvelope
  set?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  disconnect?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  delete?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  connect?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  update?: Prisma.ItemServicioClinicaUpdateWithWhereUniqueWithoutServicioInput | Prisma.ItemServicioClinicaUpdateWithWhereUniqueWithoutServicioInput[]
  updateMany?: Prisma.ItemServicioClinicaUpdateManyWithWhereWithoutServicioInput | Prisma.ItemServicioClinicaUpdateManyWithWhereWithoutServicioInput[]
  deleteMany?: Prisma.ItemServicioClinicaScalarWhereInput | Prisma.ItemServicioClinicaScalarWhereInput[]
}

export type ItemServicioClinicaUncheckedUpdateManyWithoutServicioNestedInput = {
  create?: Prisma.XOR<Prisma.ItemServicioClinicaCreateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput> | Prisma.ItemServicioClinicaCreateWithoutServicioInput[] | Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput[]
  connectOrCreate?: Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput | Prisma.ItemServicioClinicaCreateOrConnectWithoutServicioInput[]
  upsert?: Prisma.ItemServicioClinicaUpsertWithWhereUniqueWithoutServicioInput | Prisma.ItemServicioClinicaUpsertWithWhereUniqueWithoutServicioInput[]
  createMany?: Prisma.ItemServicioClinicaCreateManyServicioInputEnvelope
  set?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  disconnect?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  delete?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  connect?: Prisma.ItemServicioClinicaWhereUniqueInput | Prisma.ItemServicioClinicaWhereUniqueInput[]
  update?: Prisma.ItemServicioClinicaUpdateWithWhereUniqueWithoutServicioInput | Prisma.ItemServicioClinicaUpdateWithWhereUniqueWithoutServicioInput[]
  updateMany?: Prisma.ItemServicioClinicaUpdateManyWithWhereWithoutServicioInput | Prisma.ItemServicioClinicaUpdateManyWithWhereWithoutServicioInput[]
  deleteMany?: Prisma.ItemServicioClinicaScalarWhereInput | Prisma.ItemServicioClinicaScalarWhereInput[]
}

export type ItemServicioClinicaCreateWithoutServicioInput = {
  id?: string
  prendaTipo: string
  prendaDescripcion?: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemServicioClinicaUncheckedCreateWithoutServicioInput = {
  id?: string
  prendaTipo: string
  prendaDescripcion?: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemServicioClinicaCreateOrConnectWithoutServicioInput = {
  where: Prisma.ItemServicioClinicaWhereUniqueInput
  create: Prisma.XOR<Prisma.ItemServicioClinicaCreateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput>
}

export type ItemServicioClinicaCreateManyServicioInputEnvelope = {
  data: Prisma.ItemServicioClinicaCreateManyServicioInput | Prisma.ItemServicioClinicaCreateManyServicioInput[]
  skipDuplicates?: boolean
}

export type ItemServicioClinicaUpsertWithWhereUniqueWithoutServicioInput = {
  where: Prisma.ItemServicioClinicaWhereUniqueInput
  update: Prisma.XOR<Prisma.ItemServicioClinicaUpdateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedUpdateWithoutServicioInput>
  create: Prisma.XOR<Prisma.ItemServicioClinicaCreateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedCreateWithoutServicioInput>
}

export type ItemServicioClinicaUpdateWithWhereUniqueWithoutServicioInput = {
  where: Prisma.ItemServicioClinicaWhereUniqueInput
  data: Prisma.XOR<Prisma.ItemServicioClinicaUpdateWithoutServicioInput, Prisma.ItemServicioClinicaUncheckedUpdateWithoutServicioInput>
}

export type ItemServicioClinicaUpdateManyWithWhereWithoutServicioInput = {
  where: Prisma.ItemServicioClinicaScalarWhereInput
  data: Prisma.XOR<Prisma.ItemServicioClinicaUpdateManyMutationInput, Prisma.ItemServicioClinicaUncheckedUpdateManyWithoutServicioInput>
}

export type ItemServicioClinicaScalarWhereInput = {
  AND?: Prisma.ItemServicioClinicaScalarWhereInput | Prisma.ItemServicioClinicaScalarWhereInput[]
  OR?: Prisma.ItemServicioClinicaScalarWhereInput[]
  NOT?: Prisma.ItemServicioClinicaScalarWhereInput | Prisma.ItemServicioClinicaScalarWhereInput[]
  id?: Prisma.StringFilter<"ItemServicioClinica"> | string
  servicioId?: Prisma.StringFilter<"ItemServicioClinica"> | string
  prendaTipo?: Prisma.StringFilter<"ItemServicioClinica"> | string
  prendaDescripcion?: Prisma.StringNullableFilter<"ItemServicioClinica"> | string | null
  trabajoSolicitado?: Prisma.StringFilter<"ItemServicioClinica"> | string
  valorCotizado?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFilter<"ItemServicioClinica"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFilter<"ItemServicioClinica"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ItemServicioClinica"> | Date | string
}

export type ItemServicioClinicaCreateManyServicioInput = {
  id?: string
  prendaTipo: string
  prendaDescripcion?: string | null
  trabajoSolicitado: string
  valorCotizado: runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente: runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ItemServicioClinicaUpdateWithoutServicioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemServicioClinicaUncheckedUpdateWithoutServicioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ItemServicioClinicaUncheckedUpdateManyWithoutServicioInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  prendaTipo?: Prisma.StringFieldUpdateOperationsInput | string
  prendaDescripcion?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  trabajoSolicitado?: Prisma.StringFieldUpdateOperationsInput | string
  valorCotizado?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  anticipo?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  saldoPendiente?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ItemServicioClinicaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  servicioId?: boolean
  prendaTipo?: boolean
  prendaDescripcion?: boolean
  trabajoSolicitado?: boolean
  valorCotizado?: boolean
  anticipo?: boolean
  saldoPendiente?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  servicio?: boolean | Prisma.ServicioClinicaDefaultArgs<ExtArgs>
}, ExtArgs["result"]["itemServicioClinica"]>



export type ItemServicioClinicaSelectScalar = {
  id?: boolean
  servicioId?: boolean
  prendaTipo?: boolean
  prendaDescripcion?: boolean
  trabajoSolicitado?: boolean
  valorCotizado?: boolean
  anticipo?: boolean
  saldoPendiente?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ItemServicioClinicaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "servicioId" | "prendaTipo" | "prendaDescripcion" | "trabajoSolicitado" | "valorCotizado" | "anticipo" | "saldoPendiente" | "createdAt" | "updatedAt", ExtArgs["result"]["itemServicioClinica"]>
export type ItemServicioClinicaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  servicio?: boolean | Prisma.ServicioClinicaDefaultArgs<ExtArgs>
}

export type $ItemServicioClinicaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ItemServicioClinica"
  objects: {
    servicio: Prisma.$ServicioClinicaPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    servicioId: string
    prendaTipo: string
    prendaDescripcion: string | null
    trabajoSolicitado: string
    valorCotizado: runtime.Decimal
    anticipo: runtime.Decimal
    saldoPendiente: runtime.Decimal
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["itemServicioClinica"]>
  composites: {}
}

export type ItemServicioClinicaGetPayload<S extends boolean | null | undefined | ItemServicioClinicaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload, S>

export type ItemServicioClinicaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ItemServicioClinicaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ItemServicioClinicaCountAggregateInputType | true
  }

export interface ItemServicioClinicaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ItemServicioClinica'], meta: { name: 'ItemServicioClinica' } }
  /**
   * Find zero or one ItemServicioClinica that matches the filter.
   * @param {ItemServicioClinicaFindUniqueArgs} args - Arguments to find a ItemServicioClinica
   * @example
   * // Get one ItemServicioClinica
   * const itemServicioClinica = await prisma.itemServicioClinica.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ItemServicioClinicaFindUniqueArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ItemServicioClinica that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ItemServicioClinicaFindUniqueOrThrowArgs} args - Arguments to find a ItemServicioClinica
   * @example
   * // Get one ItemServicioClinica
   * const itemServicioClinica = await prisma.itemServicioClinica.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ItemServicioClinicaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemServicioClinica that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaFindFirstArgs} args - Arguments to find a ItemServicioClinica
   * @example
   * // Get one ItemServicioClinica
   * const itemServicioClinica = await prisma.itemServicioClinica.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ItemServicioClinicaFindFirstArgs>(args?: Prisma.SelectSubset<T, ItemServicioClinicaFindFirstArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ItemServicioClinica that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaFindFirstOrThrowArgs} args - Arguments to find a ItemServicioClinica
   * @example
   * // Get one ItemServicioClinica
   * const itemServicioClinica = await prisma.itemServicioClinica.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ItemServicioClinicaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ItemServicioClinicaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ItemServicioClinicas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ItemServicioClinicas
   * const itemServicioClinicas = await prisma.itemServicioClinica.findMany()
   * 
   * // Get first 10 ItemServicioClinicas
   * const itemServicioClinicas = await prisma.itemServicioClinica.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const itemServicioClinicaWithIdOnly = await prisma.itemServicioClinica.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ItemServicioClinicaFindManyArgs>(args?: Prisma.SelectSubset<T, ItemServicioClinicaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ItemServicioClinica.
   * @param {ItemServicioClinicaCreateArgs} args - Arguments to create a ItemServicioClinica.
   * @example
   * // Create one ItemServicioClinica
   * const ItemServicioClinica = await prisma.itemServicioClinica.create({
   *   data: {
   *     // ... data to create a ItemServicioClinica
   *   }
   * })
   * 
   */
  create<T extends ItemServicioClinicaCreateArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaCreateArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ItemServicioClinicas.
   * @param {ItemServicioClinicaCreateManyArgs} args - Arguments to create many ItemServicioClinicas.
   * @example
   * // Create many ItemServicioClinicas
   * const itemServicioClinica = await prisma.itemServicioClinica.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ItemServicioClinicaCreateManyArgs>(args?: Prisma.SelectSubset<T, ItemServicioClinicaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a ItemServicioClinica.
   * @param {ItemServicioClinicaDeleteArgs} args - Arguments to delete one ItemServicioClinica.
   * @example
   * // Delete one ItemServicioClinica
   * const ItemServicioClinica = await prisma.itemServicioClinica.delete({
   *   where: {
   *     // ... filter to delete one ItemServicioClinica
   *   }
   * })
   * 
   */
  delete<T extends ItemServicioClinicaDeleteArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaDeleteArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ItemServicioClinica.
   * @param {ItemServicioClinicaUpdateArgs} args - Arguments to update one ItemServicioClinica.
   * @example
   * // Update one ItemServicioClinica
   * const itemServicioClinica = await prisma.itemServicioClinica.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ItemServicioClinicaUpdateArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaUpdateArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ItemServicioClinicas.
   * @param {ItemServicioClinicaDeleteManyArgs} args - Arguments to filter ItemServicioClinicas to delete.
   * @example
   * // Delete a few ItemServicioClinicas
   * const { count } = await prisma.itemServicioClinica.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ItemServicioClinicaDeleteManyArgs>(args?: Prisma.SelectSubset<T, ItemServicioClinicaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ItemServicioClinicas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ItemServicioClinicas
   * const itemServicioClinica = await prisma.itemServicioClinica.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ItemServicioClinicaUpdateManyArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one ItemServicioClinica.
   * @param {ItemServicioClinicaUpsertArgs} args - Arguments to update or create a ItemServicioClinica.
   * @example
   * // Update or create a ItemServicioClinica
   * const itemServicioClinica = await prisma.itemServicioClinica.upsert({
   *   create: {
   *     // ... data to create a ItemServicioClinica
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ItemServicioClinica we want to update
   *   }
   * })
   */
  upsert<T extends ItemServicioClinicaUpsertArgs>(args: Prisma.SelectSubset<T, ItemServicioClinicaUpsertArgs<ExtArgs>>): Prisma.Prisma__ItemServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ItemServicioClinicaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ItemServicioClinicas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaCountArgs} args - Arguments to filter ItemServicioClinicas to count.
   * @example
   * // Count the number of ItemServicioClinicas
   * const count = await prisma.itemServicioClinica.count({
   *   where: {
   *     // ... the filter for the ItemServicioClinicas we want to count
   *   }
   * })
  **/
  count<T extends ItemServicioClinicaCountArgs>(
    args?: Prisma.Subset<T, ItemServicioClinicaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ItemServicioClinicaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ItemServicioClinica.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ItemServicioClinicaAggregateArgs>(args: Prisma.Subset<T, ItemServicioClinicaAggregateArgs>): Prisma.PrismaPromise<GetItemServicioClinicaAggregateType<T>>

  /**
   * Group by ItemServicioClinica.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ItemServicioClinicaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ItemServicioClinicaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ItemServicioClinicaGroupByArgs['orderBy'] }
      : { orderBy?: ItemServicioClinicaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ItemServicioClinicaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetItemServicioClinicaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ItemServicioClinica model
 */
readonly fields: ItemServicioClinicaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ItemServicioClinica.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ItemServicioClinicaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  servicio<T extends Prisma.ServicioClinicaDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServicioClinicaDefaultArgs<ExtArgs>>): Prisma.Prisma__ServicioClinicaClient<runtime.Types.Result.GetResult<Prisma.$ServicioClinicaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ItemServicioClinica model
 */
export interface ItemServicioClinicaFieldRefs {
  readonly id: Prisma.FieldRef<"ItemServicioClinica", 'String'>
  readonly servicioId: Prisma.FieldRef<"ItemServicioClinica", 'String'>
  readonly prendaTipo: Prisma.FieldRef<"ItemServicioClinica", 'String'>
  readonly prendaDescripcion: Prisma.FieldRef<"ItemServicioClinica", 'String'>
  readonly trabajoSolicitado: Prisma.FieldRef<"ItemServicioClinica", 'String'>
  readonly valorCotizado: Prisma.FieldRef<"ItemServicioClinica", 'Decimal'>
  readonly anticipo: Prisma.FieldRef<"ItemServicioClinica", 'Decimal'>
  readonly saldoPendiente: Prisma.FieldRef<"ItemServicioClinica", 'Decimal'>
  readonly createdAt: Prisma.FieldRef<"ItemServicioClinica", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ItemServicioClinica", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ItemServicioClinica findUnique
 */
export type ItemServicioClinicaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * Filter, which ItemServicioClinica to fetch.
   */
  where: Prisma.ItemServicioClinicaWhereUniqueInput
}

/**
 * ItemServicioClinica findUniqueOrThrow
 */
export type ItemServicioClinicaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * Filter, which ItemServicioClinica to fetch.
   */
  where: Prisma.ItemServicioClinicaWhereUniqueInput
}

/**
 * ItemServicioClinica findFirst
 */
export type ItemServicioClinicaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * Filter, which ItemServicioClinica to fetch.
   */
  where?: Prisma.ItemServicioClinicaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemServicioClinicas to fetch.
   */
  orderBy?: Prisma.ItemServicioClinicaOrderByWithRelationInput | Prisma.ItemServicioClinicaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemServicioClinicas.
   */
  cursor?: Prisma.ItemServicioClinicaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemServicioClinicas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemServicioClinicas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemServicioClinicas.
   */
  distinct?: Prisma.ItemServicioClinicaScalarFieldEnum | Prisma.ItemServicioClinicaScalarFieldEnum[]
}

/**
 * ItemServicioClinica findFirstOrThrow
 */
export type ItemServicioClinicaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * Filter, which ItemServicioClinica to fetch.
   */
  where?: Prisma.ItemServicioClinicaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemServicioClinicas to fetch.
   */
  orderBy?: Prisma.ItemServicioClinicaOrderByWithRelationInput | Prisma.ItemServicioClinicaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ItemServicioClinicas.
   */
  cursor?: Prisma.ItemServicioClinicaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemServicioClinicas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemServicioClinicas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemServicioClinicas.
   */
  distinct?: Prisma.ItemServicioClinicaScalarFieldEnum | Prisma.ItemServicioClinicaScalarFieldEnum[]
}

/**
 * ItemServicioClinica findMany
 */
export type ItemServicioClinicaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * Filter, which ItemServicioClinicas to fetch.
   */
  where?: Prisma.ItemServicioClinicaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ItemServicioClinicas to fetch.
   */
  orderBy?: Prisma.ItemServicioClinicaOrderByWithRelationInput | Prisma.ItemServicioClinicaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ItemServicioClinicas.
   */
  cursor?: Prisma.ItemServicioClinicaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ItemServicioClinicas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ItemServicioClinicas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ItemServicioClinicas.
   */
  distinct?: Prisma.ItemServicioClinicaScalarFieldEnum | Prisma.ItemServicioClinicaScalarFieldEnum[]
}

/**
 * ItemServicioClinica create
 */
export type ItemServicioClinicaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * The data needed to create a ItemServicioClinica.
   */
  data: Prisma.XOR<Prisma.ItemServicioClinicaCreateInput, Prisma.ItemServicioClinicaUncheckedCreateInput>
}

/**
 * ItemServicioClinica createMany
 */
export type ItemServicioClinicaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ItemServicioClinicas.
   */
  data: Prisma.ItemServicioClinicaCreateManyInput | Prisma.ItemServicioClinicaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ItemServicioClinica update
 */
export type ItemServicioClinicaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * The data needed to update a ItemServicioClinica.
   */
  data: Prisma.XOR<Prisma.ItemServicioClinicaUpdateInput, Prisma.ItemServicioClinicaUncheckedUpdateInput>
  /**
   * Choose, which ItemServicioClinica to update.
   */
  where: Prisma.ItemServicioClinicaWhereUniqueInput
}

/**
 * ItemServicioClinica updateMany
 */
export type ItemServicioClinicaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ItemServicioClinicas.
   */
  data: Prisma.XOR<Prisma.ItemServicioClinicaUpdateManyMutationInput, Prisma.ItemServicioClinicaUncheckedUpdateManyInput>
  /**
   * Filter which ItemServicioClinicas to update
   */
  where?: Prisma.ItemServicioClinicaWhereInput
  /**
   * Limit how many ItemServicioClinicas to update.
   */
  limit?: number
}

/**
 * ItemServicioClinica upsert
 */
export type ItemServicioClinicaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * The filter to search for the ItemServicioClinica to update in case it exists.
   */
  where: Prisma.ItemServicioClinicaWhereUniqueInput
  /**
   * In case the ItemServicioClinica found by the `where` argument doesn't exist, create a new ItemServicioClinica with this data.
   */
  create: Prisma.XOR<Prisma.ItemServicioClinicaCreateInput, Prisma.ItemServicioClinicaUncheckedCreateInput>
  /**
   * In case the ItemServicioClinica was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ItemServicioClinicaUpdateInput, Prisma.ItemServicioClinicaUncheckedUpdateInput>
}

/**
 * ItemServicioClinica delete
 */
export type ItemServicioClinicaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
  /**
   * Filter which ItemServicioClinica to delete.
   */
  where: Prisma.ItemServicioClinicaWhereUniqueInput
}

/**
 * ItemServicioClinica deleteMany
 */
export type ItemServicioClinicaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ItemServicioClinicas to delete
   */
  where?: Prisma.ItemServicioClinicaWhereInput
  /**
   * Limit how many ItemServicioClinicas to delete.
   */
  limit?: number
}

/**
 * ItemServicioClinica without action
 */
export type ItemServicioClinicaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemServicioClinica
   */
  select?: Prisma.ItemServicioClinicaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemServicioClinica
   */
  omit?: Prisma.ItemServicioClinicaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ItemServicioClinicaInclude<ExtArgs> | null
}
