
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `OrdenProduccion` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model OrdenProduccion
 * 
 */
export type OrdenProduccionModel = runtime.Types.Result.DefaultSelection<Prisma.$OrdenProduccionPayload>

export type AggregateOrdenProduccion = {
  _count: OrdenProduccionCountAggregateOutputType | null
  _min: OrdenProduccionMinAggregateOutputType | null
  _max: OrdenProduccionMaxAggregateOutputType | null
}

export type OrdenProduccionMinAggregateOutputType = {
  id: string | null
  numero: string | null
  clienteId: string | null
  fechaIngreso: Date | null
  fechaEntrega: Date | null
  estado: $Enums.EstadoOrden | null
  notas: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrdenProduccionMaxAggregateOutputType = {
  id: string | null
  numero: string | null
  clienteId: string | null
  fechaIngreso: Date | null
  fechaEntrega: Date | null
  estado: $Enums.EstadoOrden | null
  notas: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrdenProduccionCountAggregateOutputType = {
  id: number
  numero: number
  clienteId: number
  fechaIngreso: number
  fechaEntrega: number
  estado: number
  notas: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OrdenProduccionMinAggregateInputType = {
  id?: true
  numero?: true
  clienteId?: true
  fechaIngreso?: true
  fechaEntrega?: true
  estado?: true
  notas?: true
  createdAt?: true
  updatedAt?: true
}

export type OrdenProduccionMaxAggregateInputType = {
  id?: true
  numero?: true
  clienteId?: true
  fechaIngreso?: true
  fechaEntrega?: true
  estado?: true
  notas?: true
  createdAt?: true
  updatedAt?: true
}

export type OrdenProduccionCountAggregateInputType = {
  id?: true
  numero?: true
  clienteId?: true
  fechaIngreso?: true
  fechaEntrega?: true
  estado?: true
  notas?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OrdenProduccionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrdenProduccion to aggregate.
   */
  where?: Prisma.OrdenProduccionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrdenProduccions to fetch.
   */
  orderBy?: Prisma.OrdenProduccionOrderByWithRelationInput | Prisma.OrdenProduccionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrdenProduccionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrdenProduccions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrdenProduccions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned OrdenProduccions
  **/
  _count?: true | OrdenProduccionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrdenProduccionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrdenProduccionMaxAggregateInputType
}

export type GetOrdenProduccionAggregateType<T extends OrdenProduccionAggregateArgs> = {
      [P in keyof T & keyof AggregateOrdenProduccion]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrdenProduccion[P]>
    : Prisma.GetScalarType<T[P], AggregateOrdenProduccion[P]>
}




export type OrdenProduccionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrdenProduccionWhereInput
  orderBy?: Prisma.OrdenProduccionOrderByWithAggregationInput | Prisma.OrdenProduccionOrderByWithAggregationInput[]
  by: Prisma.OrdenProduccionScalarFieldEnum[] | Prisma.OrdenProduccionScalarFieldEnum
  having?: Prisma.OrdenProduccionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrdenProduccionCountAggregateInputType | true
  _min?: OrdenProduccionMinAggregateInputType
  _max?: OrdenProduccionMaxAggregateInputType
}

export type OrdenProduccionGroupByOutputType = {
  id: string
  numero: string
  clienteId: string
  fechaIngreso: Date
  fechaEntrega: Date | null
  estado: $Enums.EstadoOrden
  notas: string | null
  createdAt: Date
  updatedAt: Date
  _count: OrdenProduccionCountAggregateOutputType | null
  _min: OrdenProduccionMinAggregateOutputType | null
  _max: OrdenProduccionMaxAggregateOutputType | null
}

export type GetOrdenProduccionGroupByPayload<T extends OrdenProduccionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrdenProduccionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrdenProduccionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrdenProduccionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrdenProduccionGroupByOutputType[P]>
      }
    >
  >



export type OrdenProduccionWhereInput = {
  AND?: Prisma.OrdenProduccionWhereInput | Prisma.OrdenProduccionWhereInput[]
  OR?: Prisma.OrdenProduccionWhereInput[]
  NOT?: Prisma.OrdenProduccionWhereInput | Prisma.OrdenProduccionWhereInput[]
  id?: Prisma.StringFilter<"OrdenProduccion"> | string
  numero?: Prisma.StringFilter<"OrdenProduccion"> | string
  clienteId?: Prisma.StringFilter<"OrdenProduccion"> | string
  fechaIngreso?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  fechaEntrega?: Prisma.DateTimeNullableFilter<"OrdenProduccion"> | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFilter<"OrdenProduccion"> | $Enums.EstadoOrden
  notas?: Prisma.StringNullableFilter<"OrdenProduccion"> | string | null
  createdAt?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  cliente?: Prisma.XOR<Prisma.ClienteScalarRelationFilter, Prisma.ClienteWhereInput>
  productos?: Prisma.ProductoOrdenListRelationFilter
  gastos?: Prisma.GastoListRelationFilter
}

export type OrdenProduccionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  fechaIngreso?: Prisma.SortOrder
  fechaEntrega?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrder
  notas?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  cliente?: Prisma.ClienteOrderByWithRelationInput
  productos?: Prisma.ProductoOrdenOrderByRelationAggregateInput
  gastos?: Prisma.GastoOrderByRelationAggregateInput
  _relevance?: Prisma.OrdenProduccionOrderByRelevanceInput
}

export type OrdenProduccionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  numero?: string
  AND?: Prisma.OrdenProduccionWhereInput | Prisma.OrdenProduccionWhereInput[]
  OR?: Prisma.OrdenProduccionWhereInput[]
  NOT?: Prisma.OrdenProduccionWhereInput | Prisma.OrdenProduccionWhereInput[]
  clienteId?: Prisma.StringFilter<"OrdenProduccion"> | string
  fechaIngreso?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  fechaEntrega?: Prisma.DateTimeNullableFilter<"OrdenProduccion"> | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFilter<"OrdenProduccion"> | $Enums.EstadoOrden
  notas?: Prisma.StringNullableFilter<"OrdenProduccion"> | string | null
  createdAt?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  cliente?: Prisma.XOR<Prisma.ClienteScalarRelationFilter, Prisma.ClienteWhereInput>
  productos?: Prisma.ProductoOrdenListRelationFilter
  gastos?: Prisma.GastoListRelationFilter
}, "id" | "numero">

export type OrdenProduccionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  fechaIngreso?: Prisma.SortOrder
  fechaEntrega?: Prisma.SortOrderInput | Prisma.SortOrder
  estado?: Prisma.SortOrder
  notas?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OrdenProduccionCountOrderByAggregateInput
  _max?: Prisma.OrdenProduccionMaxOrderByAggregateInput
  _min?: Prisma.OrdenProduccionMinOrderByAggregateInput
}

export type OrdenProduccionScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrdenProduccionScalarWhereWithAggregatesInput | Prisma.OrdenProduccionScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrdenProduccionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrdenProduccionScalarWhereWithAggregatesInput | Prisma.OrdenProduccionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"OrdenProduccion"> | string
  numero?: Prisma.StringWithAggregatesFilter<"OrdenProduccion"> | string
  clienteId?: Prisma.StringWithAggregatesFilter<"OrdenProduccion"> | string
  fechaIngreso?: Prisma.DateTimeWithAggregatesFilter<"OrdenProduccion"> | Date | string
  fechaEntrega?: Prisma.DateTimeNullableWithAggregatesFilter<"OrdenProduccion"> | Date | string | null
  estado?: Prisma.EnumEstadoOrdenWithAggregatesFilter<"OrdenProduccion"> | $Enums.EstadoOrden
  notas?: Prisma.StringNullableWithAggregatesFilter<"OrdenProduccion"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"OrdenProduccion"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"OrdenProduccion"> | Date | string
}

export type OrdenProduccionCreateInput = {
  id?: string
  numero: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  cliente: Prisma.ClienteCreateNestedOneWithoutOrdenesProduccionInput
  productos?: Prisma.ProductoOrdenCreateNestedManyWithoutOrdenInput
  gastos?: Prisma.GastoCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionUncheckedCreateInput = {
  id?: string
  numero: string
  clienteId: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ProductoOrdenUncheckedCreateNestedManyWithoutOrdenInput
  gastos?: Prisma.GastoUncheckedCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cliente?: Prisma.ClienteUpdateOneRequiredWithoutOrdenesProduccionNestedInput
  productos?: Prisma.ProductoOrdenUpdateManyWithoutOrdenNestedInput
  gastos?: Prisma.GastoUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  clienteId?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ProductoOrdenUncheckedUpdateManyWithoutOrdenNestedInput
  gastos?: Prisma.GastoUncheckedUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionCreateManyInput = {
  id?: string
  numero: string
  clienteId: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrdenProduccionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrdenProduccionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  clienteId?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrdenProduccionListRelationFilter = {
  every?: Prisma.OrdenProduccionWhereInput
  some?: Prisma.OrdenProduccionWhereInput
  none?: Prisma.OrdenProduccionWhereInput
}

export type OrdenProduccionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrdenProduccionOrderByRelevanceInput = {
  fields: Prisma.OrdenProduccionOrderByRelevanceFieldEnum | Prisma.OrdenProduccionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type OrdenProduccionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  fechaIngreso?: Prisma.SortOrder
  fechaEntrega?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  notas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrdenProduccionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  fechaIngreso?: Prisma.SortOrder
  fechaEntrega?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  notas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrdenProduccionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  clienteId?: Prisma.SortOrder
  fechaIngreso?: Prisma.SortOrder
  fechaEntrega?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  notas?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrdenProduccionScalarRelationFilter = {
  is?: Prisma.OrdenProduccionWhereInput
  isNot?: Prisma.OrdenProduccionWhereInput
}

export type OrdenProduccionNullableScalarRelationFilter = {
  is?: Prisma.OrdenProduccionWhereInput | null
  isNot?: Prisma.OrdenProduccionWhereInput | null
}

export type OrdenProduccionCreateNestedManyWithoutClienteInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutClienteInput, Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput> | Prisma.OrdenProduccionCreateWithoutClienteInput[] | Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput[]
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput | Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput[]
  createMany?: Prisma.OrdenProduccionCreateManyClienteInputEnvelope
  connect?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
}

export type OrdenProduccionUncheckedCreateNestedManyWithoutClienteInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutClienteInput, Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput> | Prisma.OrdenProduccionCreateWithoutClienteInput[] | Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput[]
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput | Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput[]
  createMany?: Prisma.OrdenProduccionCreateManyClienteInputEnvelope
  connect?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
}

export type OrdenProduccionUpdateManyWithoutClienteNestedInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutClienteInput, Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput> | Prisma.OrdenProduccionCreateWithoutClienteInput[] | Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput[]
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput | Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput[]
  upsert?: Prisma.OrdenProduccionUpsertWithWhereUniqueWithoutClienteInput | Prisma.OrdenProduccionUpsertWithWhereUniqueWithoutClienteInput[]
  createMany?: Prisma.OrdenProduccionCreateManyClienteInputEnvelope
  set?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  disconnect?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  delete?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  connect?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  update?: Prisma.OrdenProduccionUpdateWithWhereUniqueWithoutClienteInput | Prisma.OrdenProduccionUpdateWithWhereUniqueWithoutClienteInput[]
  updateMany?: Prisma.OrdenProduccionUpdateManyWithWhereWithoutClienteInput | Prisma.OrdenProduccionUpdateManyWithWhereWithoutClienteInput[]
  deleteMany?: Prisma.OrdenProduccionScalarWhereInput | Prisma.OrdenProduccionScalarWhereInput[]
}

export type OrdenProduccionUncheckedUpdateManyWithoutClienteNestedInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutClienteInput, Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput> | Prisma.OrdenProduccionCreateWithoutClienteInput[] | Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput[]
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput | Prisma.OrdenProduccionCreateOrConnectWithoutClienteInput[]
  upsert?: Prisma.OrdenProduccionUpsertWithWhereUniqueWithoutClienteInput | Prisma.OrdenProduccionUpsertWithWhereUniqueWithoutClienteInput[]
  createMany?: Prisma.OrdenProduccionCreateManyClienteInputEnvelope
  set?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  disconnect?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  delete?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  connect?: Prisma.OrdenProduccionWhereUniqueInput | Prisma.OrdenProduccionWhereUniqueInput[]
  update?: Prisma.OrdenProduccionUpdateWithWhereUniqueWithoutClienteInput | Prisma.OrdenProduccionUpdateWithWhereUniqueWithoutClienteInput[]
  updateMany?: Prisma.OrdenProduccionUpdateManyWithWhereWithoutClienteInput | Prisma.OrdenProduccionUpdateManyWithWhereWithoutClienteInput[]
  deleteMany?: Prisma.OrdenProduccionScalarWhereInput | Prisma.OrdenProduccionScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EnumEstadoOrdenFieldUpdateOperationsInput = {
  set?: $Enums.EstadoOrden
}

export type OrdenProduccionCreateNestedOneWithoutProductosInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutProductosInput, Prisma.OrdenProduccionUncheckedCreateWithoutProductosInput>
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutProductosInput
  connect?: Prisma.OrdenProduccionWhereUniqueInput
}

export type OrdenProduccionUpdateOneRequiredWithoutProductosNestedInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutProductosInput, Prisma.OrdenProduccionUncheckedCreateWithoutProductosInput>
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutProductosInput
  upsert?: Prisma.OrdenProduccionUpsertWithoutProductosInput
  connect?: Prisma.OrdenProduccionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrdenProduccionUpdateToOneWithWhereWithoutProductosInput, Prisma.OrdenProduccionUpdateWithoutProductosInput>, Prisma.OrdenProduccionUncheckedUpdateWithoutProductosInput>
}

export type OrdenProduccionCreateNestedOneWithoutGastosInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutGastosInput, Prisma.OrdenProduccionUncheckedCreateWithoutGastosInput>
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutGastosInput
  connect?: Prisma.OrdenProduccionWhereUniqueInput
}

export type OrdenProduccionUpdateOneWithoutGastosNestedInput = {
  create?: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutGastosInput, Prisma.OrdenProduccionUncheckedCreateWithoutGastosInput>
  connectOrCreate?: Prisma.OrdenProduccionCreateOrConnectWithoutGastosInput
  upsert?: Prisma.OrdenProduccionUpsertWithoutGastosInput
  disconnect?: Prisma.OrdenProduccionWhereInput | boolean
  delete?: Prisma.OrdenProduccionWhereInput | boolean
  connect?: Prisma.OrdenProduccionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrdenProduccionUpdateToOneWithWhereWithoutGastosInput, Prisma.OrdenProduccionUpdateWithoutGastosInput>, Prisma.OrdenProduccionUncheckedUpdateWithoutGastosInput>
}

export type OrdenProduccionCreateWithoutClienteInput = {
  id?: string
  numero: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ProductoOrdenCreateNestedManyWithoutOrdenInput
  gastos?: Prisma.GastoCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionUncheckedCreateWithoutClienteInput = {
  id?: string
  numero: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ProductoOrdenUncheckedCreateNestedManyWithoutOrdenInput
  gastos?: Prisma.GastoUncheckedCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionCreateOrConnectWithoutClienteInput = {
  where: Prisma.OrdenProduccionWhereUniqueInput
  create: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutClienteInput, Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput>
}

export type OrdenProduccionCreateManyClienteInputEnvelope = {
  data: Prisma.OrdenProduccionCreateManyClienteInput | Prisma.OrdenProduccionCreateManyClienteInput[]
  skipDuplicates?: boolean
}

export type OrdenProduccionUpsertWithWhereUniqueWithoutClienteInput = {
  where: Prisma.OrdenProduccionWhereUniqueInput
  update: Prisma.XOR<Prisma.OrdenProduccionUpdateWithoutClienteInput, Prisma.OrdenProduccionUncheckedUpdateWithoutClienteInput>
  create: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutClienteInput, Prisma.OrdenProduccionUncheckedCreateWithoutClienteInput>
}

export type OrdenProduccionUpdateWithWhereUniqueWithoutClienteInput = {
  where: Prisma.OrdenProduccionWhereUniqueInput
  data: Prisma.XOR<Prisma.OrdenProduccionUpdateWithoutClienteInput, Prisma.OrdenProduccionUncheckedUpdateWithoutClienteInput>
}

export type OrdenProduccionUpdateManyWithWhereWithoutClienteInput = {
  where: Prisma.OrdenProduccionScalarWhereInput
  data: Prisma.XOR<Prisma.OrdenProduccionUpdateManyMutationInput, Prisma.OrdenProduccionUncheckedUpdateManyWithoutClienteInput>
}

export type OrdenProduccionScalarWhereInput = {
  AND?: Prisma.OrdenProduccionScalarWhereInput | Prisma.OrdenProduccionScalarWhereInput[]
  OR?: Prisma.OrdenProduccionScalarWhereInput[]
  NOT?: Prisma.OrdenProduccionScalarWhereInput | Prisma.OrdenProduccionScalarWhereInput[]
  id?: Prisma.StringFilter<"OrdenProduccion"> | string
  numero?: Prisma.StringFilter<"OrdenProduccion"> | string
  clienteId?: Prisma.StringFilter<"OrdenProduccion"> | string
  fechaIngreso?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  fechaEntrega?: Prisma.DateTimeNullableFilter<"OrdenProduccion"> | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFilter<"OrdenProduccion"> | $Enums.EstadoOrden
  notas?: Prisma.StringNullableFilter<"OrdenProduccion"> | string | null
  createdAt?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"OrdenProduccion"> | Date | string
}

export type OrdenProduccionCreateWithoutProductosInput = {
  id?: string
  numero: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  cliente: Prisma.ClienteCreateNestedOneWithoutOrdenesProduccionInput
  gastos?: Prisma.GastoCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionUncheckedCreateWithoutProductosInput = {
  id?: string
  numero: string
  clienteId: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  gastos?: Prisma.GastoUncheckedCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionCreateOrConnectWithoutProductosInput = {
  where: Prisma.OrdenProduccionWhereUniqueInput
  create: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutProductosInput, Prisma.OrdenProduccionUncheckedCreateWithoutProductosInput>
}

export type OrdenProduccionUpsertWithoutProductosInput = {
  update: Prisma.XOR<Prisma.OrdenProduccionUpdateWithoutProductosInput, Prisma.OrdenProduccionUncheckedUpdateWithoutProductosInput>
  create: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutProductosInput, Prisma.OrdenProduccionUncheckedCreateWithoutProductosInput>
  where?: Prisma.OrdenProduccionWhereInput
}

export type OrdenProduccionUpdateToOneWithWhereWithoutProductosInput = {
  where?: Prisma.OrdenProduccionWhereInput
  data: Prisma.XOR<Prisma.OrdenProduccionUpdateWithoutProductosInput, Prisma.OrdenProduccionUncheckedUpdateWithoutProductosInput>
}

export type OrdenProduccionUpdateWithoutProductosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cliente?: Prisma.ClienteUpdateOneRequiredWithoutOrdenesProduccionNestedInput
  gastos?: Prisma.GastoUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionUncheckedUpdateWithoutProductosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  clienteId?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gastos?: Prisma.GastoUncheckedUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionCreateWithoutGastosInput = {
  id?: string
  numero: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  cliente: Prisma.ClienteCreateNestedOneWithoutOrdenesProduccionInput
  productos?: Prisma.ProductoOrdenCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionUncheckedCreateWithoutGastosInput = {
  id?: string
  numero: string
  clienteId: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ProductoOrdenUncheckedCreateNestedManyWithoutOrdenInput
}

export type OrdenProduccionCreateOrConnectWithoutGastosInput = {
  where: Prisma.OrdenProduccionWhereUniqueInput
  create: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutGastosInput, Prisma.OrdenProduccionUncheckedCreateWithoutGastosInput>
}

export type OrdenProduccionUpsertWithoutGastosInput = {
  update: Prisma.XOR<Prisma.OrdenProduccionUpdateWithoutGastosInput, Prisma.OrdenProduccionUncheckedUpdateWithoutGastosInput>
  create: Prisma.XOR<Prisma.OrdenProduccionCreateWithoutGastosInput, Prisma.OrdenProduccionUncheckedCreateWithoutGastosInput>
  where?: Prisma.OrdenProduccionWhereInput
}

export type OrdenProduccionUpdateToOneWithWhereWithoutGastosInput = {
  where?: Prisma.OrdenProduccionWhereInput
  data: Prisma.XOR<Prisma.OrdenProduccionUpdateWithoutGastosInput, Prisma.OrdenProduccionUncheckedUpdateWithoutGastosInput>
}

export type OrdenProduccionUpdateWithoutGastosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  cliente?: Prisma.ClienteUpdateOneRequiredWithoutOrdenesProduccionNestedInput
  productos?: Prisma.ProductoOrdenUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionUncheckedUpdateWithoutGastosInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  clienteId?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ProductoOrdenUncheckedUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionCreateManyClienteInput = {
  id?: string
  numero: string
  fechaIngreso?: Date | string
  fechaEntrega?: Date | string | null
  estado?: $Enums.EstadoOrden
  notas?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrdenProduccionUpdateWithoutClienteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ProductoOrdenUpdateManyWithoutOrdenNestedInput
  gastos?: Prisma.GastoUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionUncheckedUpdateWithoutClienteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ProductoOrdenUncheckedUpdateManyWithoutOrdenNestedInput
  gastos?: Prisma.GastoUncheckedUpdateManyWithoutOrdenNestedInput
}

export type OrdenProduccionUncheckedUpdateManyWithoutClienteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.StringFieldUpdateOperationsInput | string
  fechaIngreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fechaEntrega?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  estado?: Prisma.EnumEstadoOrdenFieldUpdateOperationsInput | $Enums.EstadoOrden
  notas?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type OrdenProduccionCountOutputType
 */

export type OrdenProduccionCountOutputType = {
  productos: number
  gastos: number
}

export type OrdenProduccionCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  productos?: boolean | OrdenProduccionCountOutputTypeCountProductosArgs
  gastos?: boolean | OrdenProduccionCountOutputTypeCountGastosArgs
}

/**
 * OrdenProduccionCountOutputType without action
 */
export type OrdenProduccionCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccionCountOutputType
   */
  select?: Prisma.OrdenProduccionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OrdenProduccionCountOutputType without action
 */
export type OrdenProduccionCountOutputTypeCountProductosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProductoOrdenWhereInput
}

/**
 * OrdenProduccionCountOutputType without action
 */
export type OrdenProduccionCountOutputTypeCountGastosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GastoWhereInput
}


export type OrdenProduccionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  numero?: boolean
  clienteId?: boolean
  fechaIngreso?: boolean
  fechaEntrega?: boolean
  estado?: boolean
  notas?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
  productos?: boolean | Prisma.OrdenProduccion$productosArgs<ExtArgs>
  gastos?: boolean | Prisma.OrdenProduccion$gastosArgs<ExtArgs>
  _count?: boolean | Prisma.OrdenProduccionCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ordenProduccion"]>



export type OrdenProduccionSelectScalar = {
  id?: boolean
  numero?: boolean
  clienteId?: boolean
  fechaIngreso?: boolean
  fechaEntrega?: boolean
  estado?: boolean
  notas?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OrdenProduccionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "numero" | "clienteId" | "fechaIngreso" | "fechaEntrega" | "estado" | "notas" | "createdAt" | "updatedAt", ExtArgs["result"]["ordenProduccion"]>
export type OrdenProduccionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  cliente?: boolean | Prisma.ClienteDefaultArgs<ExtArgs>
  productos?: boolean | Prisma.OrdenProduccion$productosArgs<ExtArgs>
  gastos?: boolean | Prisma.OrdenProduccion$gastosArgs<ExtArgs>
  _count?: boolean | Prisma.OrdenProduccionCountOutputTypeDefaultArgs<ExtArgs>
}

export type $OrdenProduccionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "OrdenProduccion"
  objects: {
    cliente: Prisma.$ClientePayload<ExtArgs>
    productos: Prisma.$ProductoOrdenPayload<ExtArgs>[]
    gastos: Prisma.$GastoPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    numero: string
    clienteId: string
    fechaIngreso: Date
    fechaEntrega: Date | null
    estado: $Enums.EstadoOrden
    notas: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["ordenProduccion"]>
  composites: {}
}

export type OrdenProduccionGetPayload<S extends boolean | null | undefined | OrdenProduccionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload, S>

export type OrdenProduccionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrdenProduccionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: OrdenProduccionCountAggregateInputType | true
  }

export interface OrdenProduccionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['OrdenProduccion'], meta: { name: 'OrdenProduccion' } }
  /**
   * Find zero or one OrdenProduccion that matches the filter.
   * @param {OrdenProduccionFindUniqueArgs} args - Arguments to find a OrdenProduccion
   * @example
   * // Get one OrdenProduccion
   * const ordenProduccion = await prisma.ordenProduccion.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrdenProduccionFindUniqueArgs>(args: Prisma.SelectSubset<T, OrdenProduccionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one OrdenProduccion that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrdenProduccionFindUniqueOrThrowArgs} args - Arguments to find a OrdenProduccion
   * @example
   * // Get one OrdenProduccion
   * const ordenProduccion = await prisma.ordenProduccion.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrdenProduccionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrdenProduccionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrdenProduccion that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionFindFirstArgs} args - Arguments to find a OrdenProduccion
   * @example
   * // Get one OrdenProduccion
   * const ordenProduccion = await prisma.ordenProduccion.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrdenProduccionFindFirstArgs>(args?: Prisma.SelectSubset<T, OrdenProduccionFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first OrdenProduccion that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionFindFirstOrThrowArgs} args - Arguments to find a OrdenProduccion
   * @example
   * // Get one OrdenProduccion
   * const ordenProduccion = await prisma.ordenProduccion.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrdenProduccionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrdenProduccionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more OrdenProduccions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all OrdenProduccions
   * const ordenProduccions = await prisma.ordenProduccion.findMany()
   * 
   * // Get first 10 OrdenProduccions
   * const ordenProduccions = await prisma.ordenProduccion.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const ordenProduccionWithIdOnly = await prisma.ordenProduccion.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrdenProduccionFindManyArgs>(args?: Prisma.SelectSubset<T, OrdenProduccionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a OrdenProduccion.
   * @param {OrdenProduccionCreateArgs} args - Arguments to create a OrdenProduccion.
   * @example
   * // Create one OrdenProduccion
   * const OrdenProduccion = await prisma.ordenProduccion.create({
   *   data: {
   *     // ... data to create a OrdenProduccion
   *   }
   * })
   * 
   */
  create<T extends OrdenProduccionCreateArgs>(args: Prisma.SelectSubset<T, OrdenProduccionCreateArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many OrdenProduccions.
   * @param {OrdenProduccionCreateManyArgs} args - Arguments to create many OrdenProduccions.
   * @example
   * // Create many OrdenProduccions
   * const ordenProduccion = await prisma.ordenProduccion.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrdenProduccionCreateManyArgs>(args?: Prisma.SelectSubset<T, OrdenProduccionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a OrdenProduccion.
   * @param {OrdenProduccionDeleteArgs} args - Arguments to delete one OrdenProduccion.
   * @example
   * // Delete one OrdenProduccion
   * const OrdenProduccion = await prisma.ordenProduccion.delete({
   *   where: {
   *     // ... filter to delete one OrdenProduccion
   *   }
   * })
   * 
   */
  delete<T extends OrdenProduccionDeleteArgs>(args: Prisma.SelectSubset<T, OrdenProduccionDeleteArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one OrdenProduccion.
   * @param {OrdenProduccionUpdateArgs} args - Arguments to update one OrdenProduccion.
   * @example
   * // Update one OrdenProduccion
   * const ordenProduccion = await prisma.ordenProduccion.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrdenProduccionUpdateArgs>(args: Prisma.SelectSubset<T, OrdenProduccionUpdateArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more OrdenProduccions.
   * @param {OrdenProduccionDeleteManyArgs} args - Arguments to filter OrdenProduccions to delete.
   * @example
   * // Delete a few OrdenProduccions
   * const { count } = await prisma.ordenProduccion.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrdenProduccionDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrdenProduccionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more OrdenProduccions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many OrdenProduccions
   * const ordenProduccion = await prisma.ordenProduccion.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrdenProduccionUpdateManyArgs>(args: Prisma.SelectSubset<T, OrdenProduccionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one OrdenProduccion.
   * @param {OrdenProduccionUpsertArgs} args - Arguments to update or create a OrdenProduccion.
   * @example
   * // Update or create a OrdenProduccion
   * const ordenProduccion = await prisma.ordenProduccion.upsert({
   *   create: {
   *     // ... data to create a OrdenProduccion
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the OrdenProduccion we want to update
   *   }
   * })
   */
  upsert<T extends OrdenProduccionUpsertArgs>(args: Prisma.SelectSubset<T, OrdenProduccionUpsertArgs<ExtArgs>>): Prisma.Prisma__OrdenProduccionClient<runtime.Types.Result.GetResult<Prisma.$OrdenProduccionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of OrdenProduccions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionCountArgs} args - Arguments to filter OrdenProduccions to count.
   * @example
   * // Count the number of OrdenProduccions
   * const count = await prisma.ordenProduccion.count({
   *   where: {
   *     // ... the filter for the OrdenProduccions we want to count
   *   }
   * })
  **/
  count<T extends OrdenProduccionCountArgs>(
    args?: Prisma.Subset<T, OrdenProduccionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrdenProduccionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a OrdenProduccion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrdenProduccionAggregateArgs>(args: Prisma.Subset<T, OrdenProduccionAggregateArgs>): Prisma.PrismaPromise<GetOrdenProduccionAggregateType<T>>

  /**
   * Group by OrdenProduccion.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrdenProduccionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrdenProduccionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrdenProduccionGroupByArgs['orderBy'] }
      : { orderBy?: OrdenProduccionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrdenProduccionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrdenProduccionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the OrdenProduccion model
 */
readonly fields: OrdenProduccionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for OrdenProduccion.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrdenProduccionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  cliente<T extends Prisma.ClienteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ClienteDefaultArgs<ExtArgs>>): Prisma.Prisma__ClienteClient<runtime.Types.Result.GetResult<Prisma.$ClientePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  productos<T extends Prisma.OrdenProduccion$productosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrdenProduccion$productosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProductoOrdenPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  gastos<T extends Prisma.OrdenProduccion$gastosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrdenProduccion$gastosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GastoPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the OrdenProduccion model
 */
export interface OrdenProduccionFieldRefs {
  readonly id: Prisma.FieldRef<"OrdenProduccion", 'String'>
  readonly numero: Prisma.FieldRef<"OrdenProduccion", 'String'>
  readonly clienteId: Prisma.FieldRef<"OrdenProduccion", 'String'>
  readonly fechaIngreso: Prisma.FieldRef<"OrdenProduccion", 'DateTime'>
  readonly fechaEntrega: Prisma.FieldRef<"OrdenProduccion", 'DateTime'>
  readonly estado: Prisma.FieldRef<"OrdenProduccion", 'EstadoOrden'>
  readonly notas: Prisma.FieldRef<"OrdenProduccion", 'String'>
  readonly createdAt: Prisma.FieldRef<"OrdenProduccion", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"OrdenProduccion", 'DateTime'>
}
    

// Custom InputTypes
/**
 * OrdenProduccion findUnique
 */
export type OrdenProduccionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * Filter, which OrdenProduccion to fetch.
   */
  where: Prisma.OrdenProduccionWhereUniqueInput
}

/**
 * OrdenProduccion findUniqueOrThrow
 */
export type OrdenProduccionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * Filter, which OrdenProduccion to fetch.
   */
  where: Prisma.OrdenProduccionWhereUniqueInput
}

/**
 * OrdenProduccion findFirst
 */
export type OrdenProduccionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * Filter, which OrdenProduccion to fetch.
   */
  where?: Prisma.OrdenProduccionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrdenProduccions to fetch.
   */
  orderBy?: Prisma.OrdenProduccionOrderByWithRelationInput | Prisma.OrdenProduccionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrdenProduccions.
   */
  cursor?: Prisma.OrdenProduccionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrdenProduccions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrdenProduccions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrdenProduccions.
   */
  distinct?: Prisma.OrdenProduccionScalarFieldEnum | Prisma.OrdenProduccionScalarFieldEnum[]
}

/**
 * OrdenProduccion findFirstOrThrow
 */
export type OrdenProduccionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * Filter, which OrdenProduccion to fetch.
   */
  where?: Prisma.OrdenProduccionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrdenProduccions to fetch.
   */
  orderBy?: Prisma.OrdenProduccionOrderByWithRelationInput | Prisma.OrdenProduccionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for OrdenProduccions.
   */
  cursor?: Prisma.OrdenProduccionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrdenProduccions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrdenProduccions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrdenProduccions.
   */
  distinct?: Prisma.OrdenProduccionScalarFieldEnum | Prisma.OrdenProduccionScalarFieldEnum[]
}

/**
 * OrdenProduccion findMany
 */
export type OrdenProduccionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * Filter, which OrdenProduccions to fetch.
   */
  where?: Prisma.OrdenProduccionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of OrdenProduccions to fetch.
   */
  orderBy?: Prisma.OrdenProduccionOrderByWithRelationInput | Prisma.OrdenProduccionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing OrdenProduccions.
   */
  cursor?: Prisma.OrdenProduccionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` OrdenProduccions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` OrdenProduccions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of OrdenProduccions.
   */
  distinct?: Prisma.OrdenProduccionScalarFieldEnum | Prisma.OrdenProduccionScalarFieldEnum[]
}

/**
 * OrdenProduccion create
 */
export type OrdenProduccionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * The data needed to create a OrdenProduccion.
   */
  data: Prisma.XOR<Prisma.OrdenProduccionCreateInput, Prisma.OrdenProduccionUncheckedCreateInput>
}

/**
 * OrdenProduccion createMany
 */
export type OrdenProduccionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many OrdenProduccions.
   */
  data: Prisma.OrdenProduccionCreateManyInput | Prisma.OrdenProduccionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * OrdenProduccion update
 */
export type OrdenProduccionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * The data needed to update a OrdenProduccion.
   */
  data: Prisma.XOR<Prisma.OrdenProduccionUpdateInput, Prisma.OrdenProduccionUncheckedUpdateInput>
  /**
   * Choose, which OrdenProduccion to update.
   */
  where: Prisma.OrdenProduccionWhereUniqueInput
}

/**
 * OrdenProduccion updateMany
 */
export type OrdenProduccionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update OrdenProduccions.
   */
  data: Prisma.XOR<Prisma.OrdenProduccionUpdateManyMutationInput, Prisma.OrdenProduccionUncheckedUpdateManyInput>
  /**
   * Filter which OrdenProduccions to update
   */
  where?: Prisma.OrdenProduccionWhereInput
  /**
   * Limit how many OrdenProduccions to update.
   */
  limit?: number
}

/**
 * OrdenProduccion upsert
 */
export type OrdenProduccionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * The filter to search for the OrdenProduccion to update in case it exists.
   */
  where: Prisma.OrdenProduccionWhereUniqueInput
  /**
   * In case the OrdenProduccion found by the `where` argument doesn't exist, create a new OrdenProduccion with this data.
   */
  create: Prisma.XOR<Prisma.OrdenProduccionCreateInput, Prisma.OrdenProduccionUncheckedCreateInput>
  /**
   * In case the OrdenProduccion was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrdenProduccionUpdateInput, Prisma.OrdenProduccionUncheckedUpdateInput>
}

/**
 * OrdenProduccion delete
 */
export type OrdenProduccionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
  /**
   * Filter which OrdenProduccion to delete.
   */
  where: Prisma.OrdenProduccionWhereUniqueInput
}

/**
 * OrdenProduccion deleteMany
 */
export type OrdenProduccionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which OrdenProduccions to delete
   */
  where?: Prisma.OrdenProduccionWhereInput
  /**
   * Limit how many OrdenProduccions to delete.
   */
  limit?: number
}

/**
 * OrdenProduccion.productos
 */
export type OrdenProduccion$productosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ProductoOrden
   */
  select?: Prisma.ProductoOrdenSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ProductoOrden
   */
  omit?: Prisma.ProductoOrdenOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProductoOrdenInclude<ExtArgs> | null
  where?: Prisma.ProductoOrdenWhereInput
  orderBy?: Prisma.ProductoOrdenOrderByWithRelationInput | Prisma.ProductoOrdenOrderByWithRelationInput[]
  cursor?: Prisma.ProductoOrdenWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProductoOrdenScalarFieldEnum | Prisma.ProductoOrdenScalarFieldEnum[]
}

/**
 * OrdenProduccion.gastos
 */
export type OrdenProduccion$gastosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Gasto
   */
  select?: Prisma.GastoSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Gasto
   */
  omit?: Prisma.GastoOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GastoInclude<ExtArgs> | null
  where?: Prisma.GastoWhereInput
  orderBy?: Prisma.GastoOrderByWithRelationInput | Prisma.GastoOrderByWithRelationInput[]
  cursor?: Prisma.GastoWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GastoScalarFieldEnum | Prisma.GastoScalarFieldEnum[]
}

/**
 * OrdenProduccion without action
 */
export type OrdenProduccionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrdenProduccion
   */
  select?: Prisma.OrdenProduccionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrdenProduccion
   */
  omit?: Prisma.OrdenProduccionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrdenProduccionInclude<ExtArgs> | null
}
