
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PlantillaMedida` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PlantillaMedida
 * 
 */
export type PlantillaMedidaModel = runtime.Types.Result.DefaultSelection<Prisma.$PlantillaMedidaPayload>

export type AggregatePlantillaMedida = {
  _count: PlantillaMedidaCountAggregateOutputType | null
  _avg: PlantillaMedidaAvgAggregateOutputType | null
  _sum: PlantillaMedidaSumAggregateOutputType | null
  _min: PlantillaMedidaMinAggregateOutputType | null
  _max: PlantillaMedidaMaxAggregateOutputType | null
}

export type PlantillaMedidaAvgAggregateOutputType = {
  orden: number | null
}

export type PlantillaMedidaSumAggregateOutputType = {
  orden: number | null
}

export type PlantillaMedidaMinAggregateOutputType = {
  id: string | null
  tipoPrenda: string | null
  nombre: string | null
  unidadDefault: string | null
  orden: number | null
}

export type PlantillaMedidaMaxAggregateOutputType = {
  id: string | null
  tipoPrenda: string | null
  nombre: string | null
  unidadDefault: string | null
  orden: number | null
}

export type PlantillaMedidaCountAggregateOutputType = {
  id: number
  tipoPrenda: number
  nombre: number
  unidadDefault: number
  orden: number
  _all: number
}


export type PlantillaMedidaAvgAggregateInputType = {
  orden?: true
}

export type PlantillaMedidaSumAggregateInputType = {
  orden?: true
}

export type PlantillaMedidaMinAggregateInputType = {
  id?: true
  tipoPrenda?: true
  nombre?: true
  unidadDefault?: true
  orden?: true
}

export type PlantillaMedidaMaxAggregateInputType = {
  id?: true
  tipoPrenda?: true
  nombre?: true
  unidadDefault?: true
  orden?: true
}

export type PlantillaMedidaCountAggregateInputType = {
  id?: true
  tipoPrenda?: true
  nombre?: true
  unidadDefault?: true
  orden?: true
  _all?: true
}

export type PlantillaMedidaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlantillaMedida to aggregate.
   */
  where?: Prisma.PlantillaMedidaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlantillaMedidas to fetch.
   */
  orderBy?: Prisma.PlantillaMedidaOrderByWithRelationInput | Prisma.PlantillaMedidaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlantillaMedidaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlantillaMedidas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlantillaMedidas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PlantillaMedidas
  **/
  _count?: true | PlantillaMedidaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlantillaMedidaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlantillaMedidaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlantillaMedidaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlantillaMedidaMaxAggregateInputType
}

export type GetPlantillaMedidaAggregateType<T extends PlantillaMedidaAggregateArgs> = {
      [P in keyof T & keyof AggregatePlantillaMedida]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlantillaMedida[P]>
    : Prisma.GetScalarType<T[P], AggregatePlantillaMedida[P]>
}




export type PlantillaMedidaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlantillaMedidaWhereInput
  orderBy?: Prisma.PlantillaMedidaOrderByWithAggregationInput | Prisma.PlantillaMedidaOrderByWithAggregationInput[]
  by: Prisma.PlantillaMedidaScalarFieldEnum[] | Prisma.PlantillaMedidaScalarFieldEnum
  having?: Prisma.PlantillaMedidaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlantillaMedidaCountAggregateInputType | true
  _avg?: PlantillaMedidaAvgAggregateInputType
  _sum?: PlantillaMedidaSumAggregateInputType
  _min?: PlantillaMedidaMinAggregateInputType
  _max?: PlantillaMedidaMaxAggregateInputType
}

export type PlantillaMedidaGroupByOutputType = {
  id: string
  tipoPrenda: string
  nombre: string
  unidadDefault: string
  orden: number
  _count: PlantillaMedidaCountAggregateOutputType | null
  _avg: PlantillaMedidaAvgAggregateOutputType | null
  _sum: PlantillaMedidaSumAggregateOutputType | null
  _min: PlantillaMedidaMinAggregateOutputType | null
  _max: PlantillaMedidaMaxAggregateOutputType | null
}

export type GetPlantillaMedidaGroupByPayload<T extends PlantillaMedidaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlantillaMedidaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlantillaMedidaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlantillaMedidaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlantillaMedidaGroupByOutputType[P]>
      }
    >
  >



export type PlantillaMedidaWhereInput = {
  AND?: Prisma.PlantillaMedidaWhereInput | Prisma.PlantillaMedidaWhereInput[]
  OR?: Prisma.PlantillaMedidaWhereInput[]
  NOT?: Prisma.PlantillaMedidaWhereInput | Prisma.PlantillaMedidaWhereInput[]
  id?: Prisma.StringFilter<"PlantillaMedida"> | string
  tipoPrenda?: Prisma.StringFilter<"PlantillaMedida"> | string
  nombre?: Prisma.StringFilter<"PlantillaMedida"> | string
  unidadDefault?: Prisma.StringFilter<"PlantillaMedida"> | string
  orden?: Prisma.IntFilter<"PlantillaMedida"> | number
}

export type PlantillaMedidaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  tipoPrenda?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  unidadDefault?: Prisma.SortOrder
  orden?: Prisma.SortOrder
  _relevance?: Prisma.PlantillaMedidaOrderByRelevanceInput
}

export type PlantillaMedidaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PlantillaMedidaWhereInput | Prisma.PlantillaMedidaWhereInput[]
  OR?: Prisma.PlantillaMedidaWhereInput[]
  NOT?: Prisma.PlantillaMedidaWhereInput | Prisma.PlantillaMedidaWhereInput[]
  tipoPrenda?: Prisma.StringFilter<"PlantillaMedida"> | string
  nombre?: Prisma.StringFilter<"PlantillaMedida"> | string
  unidadDefault?: Prisma.StringFilter<"PlantillaMedida"> | string
  orden?: Prisma.IntFilter<"PlantillaMedida"> | number
}, "id">

export type PlantillaMedidaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  tipoPrenda?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  unidadDefault?: Prisma.SortOrder
  orden?: Prisma.SortOrder
  _count?: Prisma.PlantillaMedidaCountOrderByAggregateInput
  _avg?: Prisma.PlantillaMedidaAvgOrderByAggregateInput
  _max?: Prisma.PlantillaMedidaMaxOrderByAggregateInput
  _min?: Prisma.PlantillaMedidaMinOrderByAggregateInput
  _sum?: Prisma.PlantillaMedidaSumOrderByAggregateInput
}

export type PlantillaMedidaScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlantillaMedidaScalarWhereWithAggregatesInput | Prisma.PlantillaMedidaScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlantillaMedidaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlantillaMedidaScalarWhereWithAggregatesInput | Prisma.PlantillaMedidaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PlantillaMedida"> | string
  tipoPrenda?: Prisma.StringWithAggregatesFilter<"PlantillaMedida"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"PlantillaMedida"> | string
  unidadDefault?: Prisma.StringWithAggregatesFilter<"PlantillaMedida"> | string
  orden?: Prisma.IntWithAggregatesFilter<"PlantillaMedida"> | number
}

export type PlantillaMedidaCreateInput = {
  id?: string
  tipoPrenda: string
  nombre: string
  unidadDefault: string
  orden: number
}

export type PlantillaMedidaUncheckedCreateInput = {
  id?: string
  tipoPrenda: string
  nombre: string
  unidadDefault: string
  orden: number
}

export type PlantillaMedidaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tipoPrenda?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  unidadDefault?: Prisma.StringFieldUpdateOperationsInput | string
  orden?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlantillaMedidaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tipoPrenda?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  unidadDefault?: Prisma.StringFieldUpdateOperationsInput | string
  orden?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlantillaMedidaCreateManyInput = {
  id?: string
  tipoPrenda: string
  nombre: string
  unidadDefault: string
  orden: number
}

export type PlantillaMedidaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tipoPrenda?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  unidadDefault?: Prisma.StringFieldUpdateOperationsInput | string
  orden?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlantillaMedidaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tipoPrenda?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  unidadDefault?: Prisma.StringFieldUpdateOperationsInput | string
  orden?: Prisma.IntFieldUpdateOperationsInput | number
}

export type PlantillaMedidaOrderByRelevanceInput = {
  fields: Prisma.PlantillaMedidaOrderByRelevanceFieldEnum | Prisma.PlantillaMedidaOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type PlantillaMedidaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tipoPrenda?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  unidadDefault?: Prisma.SortOrder
  orden?: Prisma.SortOrder
}

export type PlantillaMedidaAvgOrderByAggregateInput = {
  orden?: Prisma.SortOrder
}

export type PlantillaMedidaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tipoPrenda?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  unidadDefault?: Prisma.SortOrder
  orden?: Prisma.SortOrder
}

export type PlantillaMedidaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  tipoPrenda?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  unidadDefault?: Prisma.SortOrder
  orden?: Prisma.SortOrder
}

export type PlantillaMedidaSumOrderByAggregateInput = {
  orden?: Prisma.SortOrder
}



export type PlantillaMedidaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  tipoPrenda?: boolean
  nombre?: boolean
  unidadDefault?: boolean
  orden?: boolean
}, ExtArgs["result"]["plantillaMedida"]>



export type PlantillaMedidaSelectScalar = {
  id?: boolean
  tipoPrenda?: boolean
  nombre?: boolean
  unidadDefault?: boolean
  orden?: boolean
}

export type PlantillaMedidaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "tipoPrenda" | "nombre" | "unidadDefault" | "orden", ExtArgs["result"]["plantillaMedida"]>

export type $PlantillaMedidaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PlantillaMedida"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    tipoPrenda: string
    nombre: string
    unidadDefault: string
    orden: number
  }, ExtArgs["result"]["plantillaMedida"]>
  composites: {}
}

export type PlantillaMedidaGetPayload<S extends boolean | null | undefined | PlantillaMedidaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload, S>

export type PlantillaMedidaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlantillaMedidaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlantillaMedidaCountAggregateInputType | true
  }

export interface PlantillaMedidaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PlantillaMedida'], meta: { name: 'PlantillaMedida' } }
  /**
   * Find zero or one PlantillaMedida that matches the filter.
   * @param {PlantillaMedidaFindUniqueArgs} args - Arguments to find a PlantillaMedida
   * @example
   * // Get one PlantillaMedida
   * const plantillaMedida = await prisma.plantillaMedida.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlantillaMedidaFindUniqueArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PlantillaMedida that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlantillaMedidaFindUniqueOrThrowArgs} args - Arguments to find a PlantillaMedida
   * @example
   * // Get one PlantillaMedida
   * const plantillaMedida = await prisma.plantillaMedida.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlantillaMedidaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlantillaMedida that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaFindFirstArgs} args - Arguments to find a PlantillaMedida
   * @example
   * // Get one PlantillaMedida
   * const plantillaMedida = await prisma.plantillaMedida.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlantillaMedidaFindFirstArgs>(args?: Prisma.SelectSubset<T, PlantillaMedidaFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PlantillaMedida that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaFindFirstOrThrowArgs} args - Arguments to find a PlantillaMedida
   * @example
   * // Get one PlantillaMedida
   * const plantillaMedida = await prisma.plantillaMedida.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlantillaMedidaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlantillaMedidaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PlantillaMedidas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PlantillaMedidas
   * const plantillaMedidas = await prisma.plantillaMedida.findMany()
   * 
   * // Get first 10 PlantillaMedidas
   * const plantillaMedidas = await prisma.plantillaMedida.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const plantillaMedidaWithIdOnly = await prisma.plantillaMedida.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlantillaMedidaFindManyArgs>(args?: Prisma.SelectSubset<T, PlantillaMedidaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PlantillaMedida.
   * @param {PlantillaMedidaCreateArgs} args - Arguments to create a PlantillaMedida.
   * @example
   * // Create one PlantillaMedida
   * const PlantillaMedida = await prisma.plantillaMedida.create({
   *   data: {
   *     // ... data to create a PlantillaMedida
   *   }
   * })
   * 
   */
  create<T extends PlantillaMedidaCreateArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaCreateArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PlantillaMedidas.
   * @param {PlantillaMedidaCreateManyArgs} args - Arguments to create many PlantillaMedidas.
   * @example
   * // Create many PlantillaMedidas
   * const plantillaMedida = await prisma.plantillaMedida.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlantillaMedidaCreateManyArgs>(args?: Prisma.SelectSubset<T, PlantillaMedidaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a PlantillaMedida.
   * @param {PlantillaMedidaDeleteArgs} args - Arguments to delete one PlantillaMedida.
   * @example
   * // Delete one PlantillaMedida
   * const PlantillaMedida = await prisma.plantillaMedida.delete({
   *   where: {
   *     // ... filter to delete one PlantillaMedida
   *   }
   * })
   * 
   */
  delete<T extends PlantillaMedidaDeleteArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaDeleteArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PlantillaMedida.
   * @param {PlantillaMedidaUpdateArgs} args - Arguments to update one PlantillaMedida.
   * @example
   * // Update one PlantillaMedida
   * const plantillaMedida = await prisma.plantillaMedida.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlantillaMedidaUpdateArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaUpdateArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PlantillaMedidas.
   * @param {PlantillaMedidaDeleteManyArgs} args - Arguments to filter PlantillaMedidas to delete.
   * @example
   * // Delete a few PlantillaMedidas
   * const { count } = await prisma.plantillaMedida.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlantillaMedidaDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlantillaMedidaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PlantillaMedidas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PlantillaMedidas
   * const plantillaMedida = await prisma.plantillaMedida.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlantillaMedidaUpdateManyArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one PlantillaMedida.
   * @param {PlantillaMedidaUpsertArgs} args - Arguments to update or create a PlantillaMedida.
   * @example
   * // Update or create a PlantillaMedida
   * const plantillaMedida = await prisma.plantillaMedida.upsert({
   *   create: {
   *     // ... data to create a PlantillaMedida
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PlantillaMedida we want to update
   *   }
   * })
   */
  upsert<T extends PlantillaMedidaUpsertArgs>(args: Prisma.SelectSubset<T, PlantillaMedidaUpsertArgs<ExtArgs>>): Prisma.Prisma__PlantillaMedidaClient<runtime.Types.Result.GetResult<Prisma.$PlantillaMedidaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PlantillaMedidas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaCountArgs} args - Arguments to filter PlantillaMedidas to count.
   * @example
   * // Count the number of PlantillaMedidas
   * const count = await prisma.plantillaMedida.count({
   *   where: {
   *     // ... the filter for the PlantillaMedidas we want to count
   *   }
   * })
  **/
  count<T extends PlantillaMedidaCountArgs>(
    args?: Prisma.Subset<T, PlantillaMedidaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlantillaMedidaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PlantillaMedida.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlantillaMedidaAggregateArgs>(args: Prisma.Subset<T, PlantillaMedidaAggregateArgs>): Prisma.PrismaPromise<GetPlantillaMedidaAggregateType<T>>

  /**
   * Group by PlantillaMedida.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlantillaMedidaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlantillaMedidaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlantillaMedidaGroupByArgs['orderBy'] }
      : { orderBy?: PlantillaMedidaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlantillaMedidaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlantillaMedidaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PlantillaMedida model
 */
readonly fields: PlantillaMedidaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PlantillaMedida.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlantillaMedidaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PlantillaMedida model
 */
export interface PlantillaMedidaFieldRefs {
  readonly id: Prisma.FieldRef<"PlantillaMedida", 'String'>
  readonly tipoPrenda: Prisma.FieldRef<"PlantillaMedida", 'String'>
  readonly nombre: Prisma.FieldRef<"PlantillaMedida", 'String'>
  readonly unidadDefault: Prisma.FieldRef<"PlantillaMedida", 'String'>
  readonly orden: Prisma.FieldRef<"PlantillaMedida", 'Int'>
}
    

// Custom InputTypes
/**
 * PlantillaMedida findUnique
 */
export type PlantillaMedidaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * Filter, which PlantillaMedida to fetch.
   */
  where: Prisma.PlantillaMedidaWhereUniqueInput
}

/**
 * PlantillaMedida findUniqueOrThrow
 */
export type PlantillaMedidaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * Filter, which PlantillaMedida to fetch.
   */
  where: Prisma.PlantillaMedidaWhereUniqueInput
}

/**
 * PlantillaMedida findFirst
 */
export type PlantillaMedidaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * Filter, which PlantillaMedida to fetch.
   */
  where?: Prisma.PlantillaMedidaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlantillaMedidas to fetch.
   */
  orderBy?: Prisma.PlantillaMedidaOrderByWithRelationInput | Prisma.PlantillaMedidaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlantillaMedidas.
   */
  cursor?: Prisma.PlantillaMedidaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlantillaMedidas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlantillaMedidas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlantillaMedidas.
   */
  distinct?: Prisma.PlantillaMedidaScalarFieldEnum | Prisma.PlantillaMedidaScalarFieldEnum[]
}

/**
 * PlantillaMedida findFirstOrThrow
 */
export type PlantillaMedidaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * Filter, which PlantillaMedida to fetch.
   */
  where?: Prisma.PlantillaMedidaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlantillaMedidas to fetch.
   */
  orderBy?: Prisma.PlantillaMedidaOrderByWithRelationInput | Prisma.PlantillaMedidaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PlantillaMedidas.
   */
  cursor?: Prisma.PlantillaMedidaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlantillaMedidas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlantillaMedidas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlantillaMedidas.
   */
  distinct?: Prisma.PlantillaMedidaScalarFieldEnum | Prisma.PlantillaMedidaScalarFieldEnum[]
}

/**
 * PlantillaMedida findMany
 */
export type PlantillaMedidaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * Filter, which PlantillaMedidas to fetch.
   */
  where?: Prisma.PlantillaMedidaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PlantillaMedidas to fetch.
   */
  orderBy?: Prisma.PlantillaMedidaOrderByWithRelationInput | Prisma.PlantillaMedidaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PlantillaMedidas.
   */
  cursor?: Prisma.PlantillaMedidaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PlantillaMedidas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PlantillaMedidas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PlantillaMedidas.
   */
  distinct?: Prisma.PlantillaMedidaScalarFieldEnum | Prisma.PlantillaMedidaScalarFieldEnum[]
}

/**
 * PlantillaMedida create
 */
export type PlantillaMedidaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * The data needed to create a PlantillaMedida.
   */
  data: Prisma.XOR<Prisma.PlantillaMedidaCreateInput, Prisma.PlantillaMedidaUncheckedCreateInput>
}

/**
 * PlantillaMedida createMany
 */
export type PlantillaMedidaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PlantillaMedidas.
   */
  data: Prisma.PlantillaMedidaCreateManyInput | Prisma.PlantillaMedidaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PlantillaMedida update
 */
export type PlantillaMedidaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * The data needed to update a PlantillaMedida.
   */
  data: Prisma.XOR<Prisma.PlantillaMedidaUpdateInput, Prisma.PlantillaMedidaUncheckedUpdateInput>
  /**
   * Choose, which PlantillaMedida to update.
   */
  where: Prisma.PlantillaMedidaWhereUniqueInput
}

/**
 * PlantillaMedida updateMany
 */
export type PlantillaMedidaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PlantillaMedidas.
   */
  data: Prisma.XOR<Prisma.PlantillaMedidaUpdateManyMutationInput, Prisma.PlantillaMedidaUncheckedUpdateManyInput>
  /**
   * Filter which PlantillaMedidas to update
   */
  where?: Prisma.PlantillaMedidaWhereInput
  /**
   * Limit how many PlantillaMedidas to update.
   */
  limit?: number
}

/**
 * PlantillaMedida upsert
 */
export type PlantillaMedidaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * The filter to search for the PlantillaMedida to update in case it exists.
   */
  where: Prisma.PlantillaMedidaWhereUniqueInput
  /**
   * In case the PlantillaMedida found by the `where` argument doesn't exist, create a new PlantillaMedida with this data.
   */
  create: Prisma.XOR<Prisma.PlantillaMedidaCreateInput, Prisma.PlantillaMedidaUncheckedCreateInput>
  /**
   * In case the PlantillaMedida was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlantillaMedidaUpdateInput, Prisma.PlantillaMedidaUncheckedUpdateInput>
}

/**
 * PlantillaMedida delete
 */
export type PlantillaMedidaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
  /**
   * Filter which PlantillaMedida to delete.
   */
  where: Prisma.PlantillaMedidaWhereUniqueInput
}

/**
 * PlantillaMedida deleteMany
 */
export type PlantillaMedidaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PlantillaMedidas to delete
   */
  where?: Prisma.PlantillaMedidaWhereInput
  /**
   * Limit how many PlantillaMedidas to delete.
   */
  limit?: number
}

/**
 * PlantillaMedida without action
 */
export type PlantillaMedidaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PlantillaMedida
   */
  select?: Prisma.PlantillaMedidaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PlantillaMedida
   */
  omit?: Prisma.PlantillaMedidaOmit<ExtArgs> | null
}
