
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Cliente
 * 
 */
export type Cliente = Prisma.ClienteModel
/**
 * Model OrdenProduccion
 * 
 */
export type OrdenProduccion = Prisma.OrdenProduccionModel
/**
 * Model ProductoOrden
 * 
 */
export type ProductoOrden = Prisma.ProductoOrdenModel
/**
 * Model Gasto
 * 
 */
export type Gasto = Prisma.GastoModel
/**
 * Model ServicioClinica
 * 
 */
export type ServicioClinica = Prisma.ServicioClinicaModel
/**
 * Model ItemServicioClinica
 * 
 */
export type ItemServicioClinica = Prisma.ItemServicioClinicaModel
/**
 * Model FotoServicio
 * 
 */
export type FotoServicio = Prisma.FotoServicioModel
/**
 * Model PedidoConfeccion
 * 
 */
export type PedidoConfeccion = Prisma.PedidoConfeccionModel
/**
 * Model MedidaSnapshot
 * 
 */
export type MedidaSnapshot = Prisma.MedidaSnapshotModel
/**
 * Model Medida
 * 
 */
export type Medida = Prisma.MedidaModel
/**
 * Model PlantillaMedida
 * 
 */
export type PlantillaMedida = Prisma.PlantillaMedidaModel
/**
 * Model Insumo
 * 
 */
export type Insumo = Prisma.InsumoModel
/**
 * Model MovimientoInventario
 * 
 */
export type MovimientoInventario = Prisma.MovimientoInventarioModel
