
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const Role = {
  ADMIN: 'ADMIN',
  OPERARIO: 'OPERARIO',
  RECEPCION: 'RECEPCION'
} as const

export type Role = (typeof Role)[keyof typeof Role]


export const TipoCliente = {
  PERSONA: 'PERSONA',
  EMPRESA: 'EMPRESA'
} as const

export type TipoCliente = (typeof TipoCliente)[keyof typeof TipoCliente]


export const EstadoOrden = {
  PENDIENTE: 'PENDIENTE',
  EN_PRODUCCION: 'EN_PRODUCCION',
  COMPLETADA: 'COMPLETADA',
  ENTREGADA: 'ENTREGADA',
  CANCELADA: 'CANCELADA'
} as const

export type EstadoOrden = (typeof EstadoOrden)[keyof typeof EstadoOrden]


export const TipoGasto = {
  FIJO: 'FIJO',
  VARIABLE: 'VARIABLE'
} as const

export type TipoGasto = (typeof TipoGasto)[keyof typeof TipoGasto]
