
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Cliente'
export type * from './models/OrdenProduccion'
export type * from './models/ProductoOrden'
export type * from './models/Gasto'
export type * from './models/ServicioClinica'
export type * from './models/ItemServicioClinica'
export type * from './models/FotoServicio'
export type * from './models/PedidoConfeccion'
export type * from './models/MedidaSnapshot'
export type * from './models/Medida'
export type * from './models/PlantillaMedida'
export type * from './models/Insumo'
export type * from './models/MovimientoInventario'
export type * from './commonInputTypes'